              
    

//-------------------------------------------------------------------------
// This document is generated by T4
// It will overwrite your changes, please keep it as it is
// <copyright company="DigitBridge">
//     Copyright (c) DigitBridge Inc.  All rights reserved.
// </copyright>
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using System.Xml.Serialization;
using Newtonsoft.Json;

using DigitBridge.Base.Utility;
using DigitBridge.CommerceCentral.YoPoco;

namespace DigitBridge.QuickBooks.Integration
{
    /// <summary>
    /// Represents a QuickBooksExportLogData.
    /// NOTE: This class is generated from a T4 template - you should not modify it manually.
    /// </summary>
    [Serializable()]
    public partial class QuickBooksExportLogData : StructureRepository<QuickBooksExportLogData>
    {
        public QuickBooksExportLogData() : base() {}
        public QuickBooksExportLogData(IDataBaseFactory dbFactory): base(dbFactory) {}

        [JsonIgnore, XmlIgnore]
        public new bool IsNew => QuickBooksExportLog.IsNew;

        [JsonIgnore, XmlIgnore]
        public new string UniqueId => QuickBooksExportLog.UniqueId;
        
			 [JsonIgnore, XmlIgnore] 
			public static string QuickBooksExportLogTable ="QuickBooksExportLog ";
			
        #region CRUD Methods

        public override bool Equals(QuickBooksExportLogData other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            if (!string.IsNullOrWhiteSpace(UniqueId) && !string.IsNullOrWhiteSpace(other.UniqueId) && !UniqueId.Equals(other.UniqueId)) return false;
            return ChildrenEquals(other);
        }
        public virtual bool ChildrenEquals(QuickBooksExportLogData other)
        {
			if (QuickBooksExportLog == null && other.QuickBooksExportLog != null || QuickBooksExportLog != null && other.QuickBooksExportLog == null) 
				return false; 
			if (QuickBooksExportLog != null && other.QuickBooksExportLog != null && !QuickBooksExportLog.Equals(other.QuickBooksExportLog)) 
				return false; 
            return true;
        }

        // Check Children table Integrity
        public override QuickBooksExportLogData CheckIntegrity()
        {
			if (QuickBooksExportLog is null) return this; 
			QuickBooksExportLog.CheckIntegrity(); 
			CheckIntegrityOthers(); 
            return this;
        }

        partial void ClearOthers();
        public override void Clear()
        {
			QuickBooksExportLog?.Clear(); 
			ClearOthers(); 
			if (_OnClear != null)
				_OnClear(this);
            return;
        }

        public override void New()
        {
            Clear();
			QuickBooksExportLog = NewQuickBooksExportLog(); 
            return;
        }

        public virtual void CopyFrom(QuickBooksExportLogData data)
        {
			CopyQuickBooksExportLogFrom(data); 
            CheckIntegrity();
            return;
        }

        public override QuickBooksExportLogData Clone()
        {
			var newData = new QuickBooksExportLogData(); 
			newData.New(); 
			newData?.CopyFrom(this); 
			newData.QuickBooksExportLog.ClearMetaData(); 
            newData.CheckIntegrity();
            return newData;
        }

        public override bool Get(long RowNum)
        {
			var obj = GetQuickBooksExportLog(RowNum); 
			if (obj is null) return false; 
			QuickBooksExportLog = obj; 
			GetOthers(); 
			if (_OnAfterLoad != null)
				_OnAfterLoad(this);
            return true;
        }

        public override bool GetById(string QuickBooksExportLogUuid)
        {
			var obj = GetQuickBooksExportLogByQuickBooksExportLogUuid(QuickBooksExportLogUuid); 
			if (obj is null) return false; 
			QuickBooksExportLog = obj; 
			GetOthers(); 
			if (_OnAfterLoad != null)
				_OnAfterLoad(this);
            return true;
        }

        protected virtual void GetOthers()
        {
            
			if (string.IsNullOrEmpty(QuickBooksExportLog.QuickBooksExportLogUuid)) return; 
        }

        public override bool Save()
        {
			if (QuickBooksExportLog is null || string.IsNullOrEmpty(QuickBooksExportLog.QuickBooksExportLogUuid)) return false; 
			CheckIntegrity();
			if (_OnBeforeSave != null)
				if (!_OnBeforeSave(this)) return false;
			dbFactory.Begin();

			 if (NeedSave(QuickBooksExportLogTable))
			{
				QuickBooksExportLog.SetDataBaseFactory(dbFactory);
				if (!QuickBooksExportLog.Save()) return false;
			}

			if (_OnSave != null)
			{
				if (!_OnSave(dbFactory, this))
				{
					dbFactory.Abort();
					return false;
				}
			}
			dbFactory.Commit(); 
			if (_OnAfterSave != null)
				_OnAfterSave(this);
            return true;
        }

        public override bool Delete()
        {
			if (QuickBooksExportLog is null || string.IsNullOrEmpty(QuickBooksExportLog.QuickBooksExportLogUuid)) return false; 
			if (_OnBeforeDelete != null)
				if (!_OnBeforeDelete(this)) return false;
			dbFactory.Begin(); 

			 if (NeedDelete(QuickBooksExportLogTable))
			{
				QuickBooksExportLog.SetDataBaseFactory(dbFactory); 
				if (QuickBooksExportLog.Delete() <= 0) return false; 
			}
			if (_OnDelete != null)
			{
				if (!_OnDelete(dbFactory, this))
				{
					dbFactory.Abort();
					return false;
				}
			}
			dbFactory.Commit(); 
			if (_OnAfterDelete != null)
				_OnAfterDelete(this);
            return true;
        }


        public override async Task<bool> GetAsync(long RowNum)
        {
			var obj = await GetQuickBooksExportLogAsync(RowNum); 
			if (obj is null) return false; 
			QuickBooksExportLog = obj; 
			await GetOthersAsync(); 
			if (_OnAfterLoad != null)
				_OnAfterLoad(this);
            return true;
        }

        public override async Task<bool> GetByIdAsync(string QuickBooksExportLogUuid)
        {
			var obj = await GetQuickBooksExportLogByQuickBooksExportLogUuidAsync(QuickBooksExportLogUuid); 
			if (obj is null) return false; 
			QuickBooksExportLog = obj; 
			await GetOthersAsync(); 
			if (_OnAfterLoad != null)
				_OnAfterLoad(this);
            return true;
        }

        protected virtual async Task GetOthersAsync()
        {
            
			if (string.IsNullOrEmpty(QuickBooksExportLog.QuickBooksExportLogUuid)) return; 
        }

        public override async Task<bool> SaveAsync()
        {
			if (QuickBooksExportLog is null || string.IsNullOrEmpty(QuickBooksExportLog.QuickBooksExportLogUuid)) return false; 
			CheckIntegrity(); 
			if (_OnBeforeSave != null)
				if (!_OnBeforeSave(this)) return false;
			dbFactory.Begin(); 

			 if (NeedSave(QuickBooksExportLogTable))
			{
				QuickBooksExportLog.SetDataBaseFactory(dbFactory); 
				if (!(await QuickBooksExportLog.SaveAsync())) return false; 
			}
			if (_OnSave != null)
			{
				if (!_OnSave(dbFactory, this))
				{
					dbFactory.Abort();
					return false;
				}
			}
			dbFactory.Commit(); 
			if (_OnAfterSave != null)
				_OnAfterSave(this);
            return true;
        }

        public override async Task<bool> DeleteAsync()
        {
			if (QuickBooksExportLog is null || string.IsNullOrEmpty(QuickBooksExportLog.QuickBooksExportLogUuid)) return false; 
			if (_OnBeforeDelete != null)
				if (!_OnBeforeDelete(this)) return false;
			dbFactory.Begin(); 
			 if (NeedDelete(QuickBooksExportLogTable))
			{
			QuickBooksExportLog.SetDataBaseFactory(dbFactory); 
			if ((await QuickBooksExportLog.DeleteAsync()) <= 0) return false; 
			}
			if (_OnDelete != null)
			{
				if (!_OnDelete(dbFactory, this))
				{
					dbFactory.Abort();
					return false;
				}
			}
			dbFactory.Commit(); 
			if (_OnAfterDelete != null)
				_OnAfterDelete(this);
            return true;
        }

        #endregion CRUD Methods


        #region QuickBooksExportLog - Generated 
    

        // one to one children
        protected QuickBooksExportLog _QuickBooksExportLog;

        public virtual QuickBooksExportLog QuickBooksExportLog 
        { 
            get => _QuickBooksExportLog;
            set => _QuickBooksExportLog = value?.SetParent(this); 
        }

        public virtual void CopyQuickBooksExportLogFrom(QuickBooksExportLogData data) => 
            QuickBooksExportLog?.CopyFrom(data.QuickBooksExportLog, new string[] {"QuickBooksExportLogUuid"});

        public virtual QuickBooksExportLog NewQuickBooksExportLog() => new QuickBooksExportLog(dbFactory).SetParent(this);

        public virtual QuickBooksExportLog GetQuickBooksExportLog(long RowNum) =>
            (RowNum <= 0) ? null : dbFactory.Get<QuickBooksExportLog>(RowNum);

        public virtual QuickBooksExportLog GetQuickBooksExportLogByQuickBooksExportLogUuid(string QuickBooksExportLogUuid) =>
            (string.IsNullOrEmpty(QuickBooksExportLogUuid)) ? null : dbFactory.GetById<QuickBooksExportLog>(QuickBooksExportLogUuid);

        public virtual bool SaveQuickBooksExportLog(QuickBooksExportLog data) =>
            (data is null) ? false : data.Save();

        public virtual int DeleteQuickBooksExportLog(QuickBooksExportLog data) =>
            (data is null) ? 0 : data.Delete();

        public virtual async Task<QuickBooksExportLog> GetQuickBooksExportLogAsync(long RowNum) =>
            (RowNum <= 0) ? null : await dbFactory.GetAsync<QuickBooksExportLog>(RowNum);

        public virtual async Task<QuickBooksExportLog> GetQuickBooksExportLogByQuickBooksExportLogUuidAsync(string QuickBooksExportLogUuid) =>
            (string.IsNullOrEmpty(QuickBooksExportLogUuid)) ? null : await dbFactory.GetByIdAsync<QuickBooksExportLog>(QuickBooksExportLogUuid);

        public virtual async Task<bool> SaveQuickBooksExportLogAsync(QuickBooksExportLog data) =>
            (data is null) ? false : await data.SaveAsync();

        public virtual async Task<int> DeleteQuickBooksExportLogAsync(QuickBooksExportLog data) =>
            (data is null) ? 0 : await data.DeleteAsync();




        #endregion QuickBooksExportLog - Generated 


    }
}



