import { ScreenType, ProcessMode } from '../../types/enums';
import { DbComponentEnums, Enums } from '../../types';
import { IconNames } from '../../components/icon';
import { btnSave, btnEdit, btnList, btnDelete } from '../default';
import * as util from '../../util';

export const miscInvoiceUi = { 
    page: {
        screenType: ScreenType.PROCESSING,
        screenid: 1001,
        processMode: ProcessMode.LIST,
        processModeList: [Enums.ProcessMode.LIST],
        title: 'MiscInvoice',
        subTitle: '',
        readonly: false,
    },
    header: {
        title: 'MiscInvoice',
    },
    navbar: {},
    section: {},
    buttonGroup: {},
    buttons: {
        btnSave,
        btnEdit, 
        btnList, 
        btnDelete,
    },
	ui: {
		//#region UI control for MiscInvoiceHeader
		miscInvoiceNumber: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'miscInvoiceNumber',
			label: 'miscInvoiceNumber',
			placeholder: 'miscInvoiceNumber',
			maxLength: 50,
			textStyle: {},
		},
		qboDocNumber: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'qboDocNumber',
			label: 'qboDocNumber',
			placeholder: 'qboDocNumber',
			maxLength: 50,
			textStyle: {},
		},
		miscInvoiceType: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'miscInvoiceHeader',
			name: 'miscInvoiceType',
			label: 'miscInvoiceType',
			placeholder: 'miscInvoiceType',
			format: 'number',
			textStyle: {},
		},
		miscInvoiceStatus: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'miscInvoiceHeader',
			name: 'miscInvoiceStatus',
			label: 'miscInvoiceStatus',
			placeholder: 'miscInvoiceStatus',
			format: 'number',
			textStyle: {},
		},
		miscInvoiceDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'miscInvoiceHeader',
			name: 'miscInvoiceDate',
			label: 'miscInvoiceDate',
			placeholder: 'miscInvoiceDate',
			format: 'date',
			textStyle: {},
		},
		miscInvoiceTime: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'miscInvoiceTime',
			label: 'miscInvoiceTime',
			placeholder: 'miscInvoiceTime',
			format: 'time',
			textStyle: {},
		},
		customerCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'customerCode',
			label: 'customerCode',
			placeholder: 'customerCode',
			maxLength: 50,
			textStyle: {},
		},
		customerName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'customerName',
			label: 'customerName',
			placeholder: 'customerName',
			maxLength: 200,
			textStyle: {},
		},
		notes: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'notes',
			label: 'notes',
			placeholder: 'notes',
			maxLength: 500,
			textStyle: {},
		},
		paidBy: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'miscInvoiceHeader',
			name: 'paidBy',
			label: 'paidBy',
			placeholder: 'paidBy',
			format: 'number',
			textStyle: {},
		},
		bankAccountCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'bankAccountCode',
			label: 'bankAccountCode',
			placeholder: 'bankAccountCode',
			maxLength: 50,
			textStyle: {},
		},
		checkNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'checkNum',
			label: 'checkNum',
			placeholder: 'checkNum',
			maxLength: 100,
			textStyle: {},
		},
		authCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'authCode',
			label: 'authCode',
			placeholder: 'authCode',
			maxLength: 100,
			textStyle: {},
		},
		currency: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'currency',
			label: 'currency',
			placeholder: 'currency',
			maxLength: 10,
			textStyle: {},
		},
		totalAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'miscInvoiceHeader',
			name: 'totalAmount',
			label: 'totalAmount',
			placeholder: 'totalAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		paidAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'miscInvoiceHeader',
			name: 'paidAmount',
			label: 'paidAmount',
			placeholder: 'paidAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		creditAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'miscInvoiceHeader',
			name: 'creditAmount',
			label: 'creditAmount',
			placeholder: 'creditAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		balance: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'miscInvoiceHeader',
			name: 'balance',
			label: 'balance',
			placeholder: 'balance',
			format: 'decimalNumber',
			textStyle: {},
		},
		invoiceSourceCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'invoiceSourceCode',
			label: 'invoiceSourceCode',
			placeholder: 'invoiceSourceCode',
			maxLength: 100,
			textStyle: {},
		},
		updateDateUtc: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'miscInvoiceHeader',
			name: 'updateDateUtc',
			label: 'updateDateUtc',
			placeholder: 'updateDateUtc',
			format: 'date',
			textStyle: {},
		},
		enterBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'enterBy',
			label: 'enterBy',
			placeholder: 'enterBy',
			maxLength: 100,
			textStyle: {},
		},
		updateBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'miscInvoiceHeader',
			name: 'updateBy',
			label: 'updateBy',
			placeholder: 'updateBy',
			maxLength: 100,
			textStyle: {},
		},
		//#endregion UI control for MiscInvoiceHeader



	},

    grid: {
    },
    modal: {},
    menu: {},
};

