import { DbComponentEnums } from '../../types';
import { IconNames } from '../../components/icon';
import * as util from '../../util';

//#region all grid columns for OrderShipmentPackage
/** copy column's define object to gridColumns will display column in screen.
const allColumns = [
	{
		id: 'rid',
		name: 'rid',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.hiden,
		defaultFlex: 1,
		systemHide: true,
	},
	{
		id: 'rno',
		name: 'rno',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.rowNo,
		header: '#',
		align: DbComponentEnums.alignEnum.center,
		defaultFlex: 1,
		textStyle: {},
		sortable: false,
		hide: true,
	},
	{
		id: 'orderShipmentPackageNum',
		name: 'orderShipmentPackageNum',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'orderShipmentPackageNum',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'orderShipmentNum',
		name: 'orderShipmentNum',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'orderShipmentNum',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageID',
		name: 'packageID',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageID',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageType',
		name: 'packageType',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageType',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packagePatternNum',
		name: 'packagePatternNum',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packagePatternNum',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageTrackingNumber',
		name: 'packageTrackingNumber',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageTrackingNumber',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageReturnTrackingNumber',
		name: 'packageReturnTrackingNumber',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageReturnTrackingNumber',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageWeight',
		name: 'packageWeight',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageWeight',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageLength',
		name: 'packageLength',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageLength',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageWidth',
		name: 'packageWidth',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageWidth',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageHeight',
		name: 'packageHeight',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageHeight',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageVolume',
		name: 'packageVolume',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageVolume',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packageQty',
		name: 'packageQty',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packageQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'parentPackageNum',
		name: 'parentPackageNum',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'parentPackageNum',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'hasChildPackage',
		name: 'hasChildPackage',
		parentName: 'orderShipmentPackage',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'hasChildPackage',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
];
*/
//#endregion all grid columns for OrderShipmentPackage
// display columns in screen grid
const gridColumns: any[] = [
];

export const orderShipmentPackageGrid = { 
	grid: {
        name: 'orderShipmentPackage',
	    idProperty: 'rid',
        // className: '',
        // bgColor: '',
        // color: '',
        // width: '100%',
        // minWidth: null,
        height: 500,
        // minHeight: 500,

        // hide: false,
        // systemHide?: false,
        // readOnly?: false,
        // reverseScreenReadOnly?: false,
        // disabled?: false,

        // enableEip: true,
        // enableSort: true,
        // enableSelect: true,
        // enableInsert: true,
        // enableDelete: true,
        // showRowNo: true,
        // enableRowNoButton: true,      // Add row no as button. { name: `btnRowNo_${gridName}`, moreData: { gridName, rid } }

        columns: gridColumns,
	},
	editor: {
	//#region grid editor for OrderShipmentPackage
	orderShipmentPackageNum: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'orderShipmentPackageNum',
		placeholder: 'orderShipmentPackageNum',
		format: 'number',
		textStyle: {},
	},
	orderShipmentNum: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'orderShipmentNum',
		placeholder: 'orderShipmentNum',
		format: 'number',
		textStyle: {},
	},
	packageID: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'orderShipmentPackage',
		name: 'packageID',
		placeholder: 'packageID',
		maxLength: 50,
		textStyle: {},
	},
	packageType: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'packageType',
		placeholder: 'packageType',
		format: 'number',
		textStyle: {},
	},
	packagePatternNum: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'packagePatternNum',
		placeholder: 'packagePatternNum',
		format: 'number',
		textStyle: {},
	},
	packageTrackingNumber: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'orderShipmentPackage',
		name: 'packageTrackingNumber',
		placeholder: 'packageTrackingNumber',
		maxLength: 50,
		textStyle: {},
	},
	packageReturnTrackingNumber: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'orderShipmentPackage',
		name: 'packageReturnTrackingNumber',
		placeholder: 'packageReturnTrackingNumber',
		maxLength: 50,
		textStyle: {},
	},
	packageWeight: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'packageWeight',
		placeholder: 'packageWeight',
		format: 'decimalNumber',
		textStyle: {},
	},
	packageLength: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'packageLength',
		placeholder: 'packageLength',
		format: 'decimalNumber',
		textStyle: {},
	},
	packageWidth: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'packageWidth',
		placeholder: 'packageWidth',
		format: 'decimalNumber',
		textStyle: {},
	},
	packageHeight: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'packageHeight',
		placeholder: 'packageHeight',
		format: 'decimalNumber',
		textStyle: {},
	},
	packageVolume: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'packageVolume',
		placeholder: 'packageVolume',
		format: 'decimalNumber',
		textStyle: {},
	},
	packageQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'packageQty',
		placeholder: 'packageQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	parentPackageNum: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentPackage',
		name: 'parentPackageNum',
		placeholder: 'parentPackageNum',
		format: 'number',
		textStyle: {},
	},
	hasChildPackage: {
		type: DbComponentEnums.inputTypeEnum.checkbox,
		parentName: 'orderShipmentPackage',
		name: 'hasChildPackage',
		placeholder: 'hasChildPackage',
		textStyle: {},
	},
	//#endregion grid editor for OrderShipmentPackage
	}
};



