import { DbComponentEnums } from '../../types';
import { IconNames } from '../../components/icon';
import * as util from '../../util';

//#region all grid columns for OrderShipmentCanceledItem
/** copy column's define object to gridColumns will display column in screen.
const allColumns = [
	{
		id: 'rid',
		name: 'rid',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.hiden,
		defaultFlex: 1,
		systemHide: true,
	},
	{
		id: 'rno',
		name: 'rno',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.rowNo,
		header: '#',
		align: DbComponentEnums.alignEnum.center,
		defaultFlex: 1,
		textStyle: {},
		sortable: false,
		hide: true,
	},
	{
		id: 'orderShipmentCanceledItemNum',
		name: 'orderShipmentCanceledItemNum',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'orderShipmentCanceledItemNum',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'orderShipmentNum',
		name: 'orderShipmentNum',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'orderShipmentNum',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'channelOrderID',
		name: 'channelOrderID',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'channelOrderID',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'orderDCAssignmentLineNum',
		name: 'orderDCAssignmentLineNum',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'orderDCAssignmentLineNum',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'sku',
		name: 'sku',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'sku',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'canceledQty',
		name: 'canceledQty',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'canceledQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'cancelCode',
		name: 'cancelCode',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'cancelCode',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'cancelOtherReason',
		name: 'cancelOtherReason',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'cancelOtherReason',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'dBChannelOrderLineRowID',
		name: 'dBChannelOrderLineRowID',
		parentName: 'orderShipmentCanceledItem',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'dBChannelOrderLineRowID',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
];
*/
//#endregion all grid columns for OrderShipmentCanceledItem
// display columns in screen grid
const gridColumns: any[] = [
];

export const orderShipmentCanceledItemGrid = { 
	grid: {
        name: 'orderShipmentCanceledItem',
	    idProperty: 'rid',
        // className: '',
        // bgColor: '',
        // color: '',
        // width: '100%',
        // minWidth: null,
        height: 500,
        // minHeight: 500,

        // hide: false,
        // systemHide?: false,
        // readOnly?: false,
        // reverseScreenReadOnly?: false,
        // disabled?: false,

        // enableEip: true,
        // enableSort: true,
        // enableSelect: true,
        // enableInsert: true,
        // enableDelete: true,
        // showRowNo: true,
        // enableRowNoButton: true,      // Add row no as button. { name: `btnRowNo_${gridName}`, moreData: { gridName, rid } }

        columns: gridColumns,
	},
	editor: {
	//#region grid editor for OrderShipmentCanceledItem
	orderShipmentCanceledItemNum: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentCanceledItem',
		name: 'orderShipmentCanceledItemNum',
		placeholder: 'orderShipmentCanceledItemNum',
		format: 'number',
		textStyle: {},
	},
	orderShipmentNum: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentCanceledItem',
		name: 'orderShipmentNum',
		placeholder: 'orderShipmentNum',
		format: 'number',
		textStyle: {},
	},
	channelOrderID: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'orderShipmentCanceledItem',
		name: 'channelOrderID',
		placeholder: 'channelOrderID',
		maxLength: 130,
		textStyle: {},
	},
	orderDCAssignmentLineNum: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentCanceledItem',
		name: 'orderDCAssignmentLineNum',
		placeholder: 'orderDCAssignmentLineNum',
		format: 'number',
		textStyle: {},
	},
	sku: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'orderShipmentCanceledItem',
		name: 'sku',
		placeholder: 'sku',
		maxLength: 100,
		textStyle: {},
	},
	canceledQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'orderShipmentCanceledItem',
		name: 'canceledQty',
		placeholder: 'canceledQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	cancelCode: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'orderShipmentCanceledItem',
		name: 'cancelCode',
		placeholder: 'cancelCode',
		maxLength: 50,
		textStyle: {},
	},
	cancelOtherReason: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'orderShipmentCanceledItem',
		name: 'cancelOtherReason',
		placeholder: 'cancelOtherReason',
		maxLength: 200,
		textStyle: {},
	},
	dBChannelOrderLineRowID: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'orderShipmentCanceledItem',
		name: 'dBChannelOrderLineRowID',
		placeholder: 'dBChannelOrderLineRowID',
		maxLength: 50,
		textStyle: {},
	},
	//#endregion grid editor for OrderShipmentCanceledItem
	}
};



