import { ScreenType, ProcessMode } from '../../types/enums';
import { DbComponentEnums, Enums } from '../../types';
import { IconNames } from '../../components/icon';
import { btnSave, btnEdit, btnList, btnDelete } from '../default';
import * as util from '../../util';

import { orderShipmentCanceledItemGrid } from './orderShipmentCanceledItem.grid';
import { orderShipmentPackageGrid } from './orderShipmentPackage.grid';
export const orderShipmentUi = { 
    page: {
        screenType: ScreenType.PROCESSING,
        screenid: 1001,
        processMode: ProcessMode.LIST,
        processModeList: [Enums.ProcessMode.LIST],
        title: 'OrderShipment',
        subTitle: '',
        readonly: false,
    },
    header: {
        title: 'OrderShipment',
    },
    navbar: {},
    section: {},
    buttonGroup: {},
    buttons: {
        btnSave,
        btnEdit, 
        btnList, 
        btnDelete,
    },
	ui: {
		//#region UI control for OrderShipmentHeader
		orderShipmentNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'orderShipmentNum',
			label: 'orderShipmentNum',
			placeholder: 'orderShipmentNum',
			format: 'number',
			textStyle: {},
		},
		orderDCAssignmentNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'orderDCAssignmentNum',
			label: 'orderDCAssignmentNum',
			placeholder: 'orderDCAssignmentNum',
			format: 'number',
			textStyle: {},
		},
		centralOrderNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'centralOrderNum',
			label: 'centralOrderNum',
			placeholder: 'centralOrderNum',
			format: 'number',
			textStyle: {},
		},
		channelOrderID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'channelOrderID',
			label: 'channelOrderID',
			placeholder: 'channelOrderID',
			maxLength: 130,
			textStyle: {},
		},
		shipmentID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'shipmentID',
			label: 'shipmentID',
			placeholder: 'shipmentID',
			maxLength: 50,
			textStyle: {},
		},
		warehouseCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'warehouseCode',
			label: 'warehouseCode',
			placeholder: 'warehouseCode',
			maxLength: 50,
			textStyle: {},
		},
		shipmentType: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'shipmentType',
			label: 'shipmentType',
			placeholder: 'shipmentType',
			format: 'number',
			textStyle: {},
		},
		shipmentReferenceID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'shipmentReferenceID',
			label: 'shipmentReferenceID',
			placeholder: 'shipmentReferenceID',
			maxLength: 50,
			textStyle: {},
		},
		shipmentDateUtc: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'orderShipmentHeader',
			name: 'shipmentDateUtc',
			label: 'shipmentDateUtc',
			placeholder: 'shipmentDateUtc',
			format: 'date',
			textStyle: {},
		},
		shippingCarrier: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'shippingCarrier',
			label: 'shippingCarrier',
			placeholder: 'shippingCarrier',
			maxLength: 50,
			textStyle: {},
		},
		shippingClass: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'shippingClass',
			label: 'shippingClass',
			placeholder: 'shippingClass',
			maxLength: 50,
			textStyle: {},
		},
		shippingCost: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'shippingCost',
			label: 'shippingCost',
			placeholder: 'shippingCost',
			format: 'cost',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		mainTrackingNumber: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'mainTrackingNumber',
			label: 'mainTrackingNumber',
			placeholder: 'mainTrackingNumber',
			maxLength: 50,
			textStyle: {},
		},
		mainReturnTrackingNumber: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'mainReturnTrackingNumber',
			label: 'mainReturnTrackingNumber',
			placeholder: 'mainReturnTrackingNumber',
			maxLength: 50,
			textStyle: {},
		},
		billOfLadingID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'billOfLadingID',
			label: 'billOfLadingID',
			placeholder: 'billOfLadingID',
			maxLength: 50,
			textStyle: {},
		},
		totalPackages: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'totalPackages',
			label: 'totalPackages',
			placeholder: 'totalPackages',
			format: 'number',
			textStyle: {},
		},
		totalShippedQty: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'totalShippedQty',
			label: 'totalShippedQty',
			placeholder: 'totalShippedQty',
			format: 'qty',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		totalCanceledQty: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'totalCanceledQty',
			label: 'totalCanceledQty',
			placeholder: 'totalCanceledQty',
			format: 'qty',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		totalWeight: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'totalWeight',
			label: 'totalWeight',
			placeholder: 'totalWeight',
			format: 'decimalNumber',
			textStyle: {},
		},
		totalVolume: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'totalVolume',
			label: 'totalVolume',
			placeholder: 'totalVolume',
			format: 'decimalNumber',
			textStyle: {},
		},
		weightUnit: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'weightUnit',
			label: 'weightUnit',
			placeholder: 'weightUnit',
			format: 'number',
			textStyle: {},
		},
		lengthUnit: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'lengthUnit',
			label: 'lengthUnit',
			placeholder: 'lengthUnit',
			format: 'number',
			textStyle: {},
		},
		volumeUnit: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'volumeUnit',
			label: 'volumeUnit',
			placeholder: 'volumeUnit',
			format: 'number',
			textStyle: {},
		},
		shipmentStatus: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'shipmentStatus',
			label: 'shipmentStatus',
			placeholder: 'shipmentStatus',
			format: 'number',
			textStyle: {},
		},
		dBChannelOrderHeaderRowID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'dBChannelOrderHeaderRowID',
			label: 'dBChannelOrderHeaderRowID',
			placeholder: 'dBChannelOrderHeaderRowID',
			maxLength: 50,
			textStyle: {},
		},
		processStatus: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'orderShipmentHeader',
			name: 'processStatus',
			label: 'processStatus',
			placeholder: 'processStatus',
			format: 'number',
			textStyle: {},
		},
		processDateUtc: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'orderShipmentHeader',
			name: 'processDateUtc',
			label: 'processDateUtc',
			placeholder: 'processDateUtc',
			format: 'date',
			textStyle: {},
		},
		invoiceNumber: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'invoiceNumber',
			label: 'invoiceNumber',
			placeholder: 'invoiceNumber',
			maxLength: 50,
			textStyle: {},
		},
		orderNumber: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'orderShipmentHeader',
			name: 'orderNumber',
			label: 'orderNumber',
			placeholder: 'orderNumber',
			maxLength: 50,
			textStyle: {},
		},
		//#endregion UI control for OrderShipmentHeader



	},

    grid: {
		orderShipmentCanceledItem: orderShipmentCanceledItemGrid,
		orderShipmentPackage: orderShipmentPackageGrid,
    },
    modal: {},
    menu: {},
};

