              
//-------------------------------------------------------------------------
// This document is generated by T4
// It will overwrite your changes, please keep it as it is
// <copyright company="DigitBridge">
//     Copyright (c) DigitBridge Inc.  All rights reserved.
// </copyright>
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using DigitBridge.Base.Common;
using DigitBridge.Base.Utility;
using DigitBridge.CommerceCentral.ERPDb;
using DigitBridge.CommerceCentral.YoPoco;
using Helper = DigitBridge.CommerceCentral.ERPDb.PoHeaderHelper;
using ItemsHelper = DigitBridge.CommerceCentral.ERPDb.PoItemsHelper;

namespace DigitBridge.CommerceCentral.ERPMdl
{
    public class WmsPurchaseOrderQuery : QueryObject<WmsPurchaseOrderQuery>
    {
        // Table prefix which use in this sql query
        protected static string PREFIX = Helper.TableAllies;
        protected static string ITEMSPREFIX = ItemsHelper.TableAllies;

        // Filter fields
        protected QueryFilter<DateTime> _UpdateDateFrom = new QueryFilter<DateTime>("UpdateDateFrom", "UpdateDateUtc", PREFIX, FilterBy.ge, SqlQuery._SqlMinDateTime,isDate:true);
        public QueryFilter<DateTime> UpdateDateFrom => _UpdateDateFrom;

        protected QueryFilter<DateTime> _UpdateDateTo = new QueryFilter<DateTime>("UpdateDateTo", "UpdateDateUtc", PREFIX, FilterBy.le, SqlQuery._AppMaxDateTime,isDate:true);
        public QueryFilter<DateTime> UpdateDateTo => _UpdateDateTo;

         
        
        public WmsPurchaseOrderQuery() : base(PREFIX)
        {
            AddFilter(_UpdateDateFrom);
            AddFilter(_UpdateDateTo);
        }

        public override void InitQueryFilter()
        {
            _UpdateDateFrom.FilterValue = DateTime.Now.AddDays(-1);
            _UpdateDateTo.FilterValue = DateTime.Now;
        }
    }
}
