import { DbComponentEnums } from '../../types';
import { IconNames } from '../../components/icon';
import * as util from '../../util';

//#region all grid columns for CustomerAddress
/** copy column's define object to gridColumns will display column in screen.
const allColumns = [
	{
		id: 'rid',
		name: 'rid',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.hiden,
		defaultFlex: 1,
		systemHide: true,
	},
	{
		id: 'rno',
		name: 'rno',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.rowNo,
		header: '#',
		align: DbComponentEnums.alignEnum.center,
		defaultFlex: 1,
		textStyle: {},
		sortable: false,
		hide: true,
	},
	{
		id: 'addressCode',
		name: 'addressCode',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'addressCode',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'addressType',
		name: 'addressType',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'addressType',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'description',
		name: 'description',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'description',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'name',
		name: 'name',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'name',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'company',
		name: 'company',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'company',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'companyJobTitle',
		name: 'companyJobTitle',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'companyJobTitle',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'attention',
		name: 'attention',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'attention',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'addressLine1',
		name: 'addressLine1',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'addressLine1',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'addressLine2',
		name: 'addressLine2',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'addressLine2',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'city',
		name: 'city',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'city',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'state',
		name: 'state',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'state',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'stateFullName',
		name: 'stateFullName',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'stateFullName',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'postalCode',
		name: 'postalCode',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'postalCode',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'postalCodeExt',
		name: 'postalCodeExt',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'postalCodeExt',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'county',
		name: 'county',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'county',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'country',
		name: 'country',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'country',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'email',
		name: 'email',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'email',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'daytimePhone',
		name: 'daytimePhone',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'daytimePhone',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'nightPhone',
		name: 'nightPhone',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'nightPhone',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updateDateUtc',
		name: 'updateDateUtc',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updateDateUtc',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'enterBy',
		name: 'enterBy',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'enterBy',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updateBy',
		name: 'updateBy',
		parentName: 'customerAddress',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updateBy',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
];
*/
//#endregion all grid columns for CustomerAddress
// display columns in screen grid
const gridColumns: any[] = [
];

export const customerAddressGrid = { 
	grid: {
        name: 'customerAddress',
	    idProperty: 'rid',
        // className: '',
        // bgColor: '',
        // color: '',
        // width: '100%',
        // minWidth: null,
        height: 500,
        // minHeight: 500,

        // hide: false,
        // systemHide?: false,
        // readOnly?: false,
        // reverseScreenReadOnly?: false,
        // disabled?: false,

        // enableEip: true,
        // enableSort: true,
        // enableSelect: true,
        // enableInsert: true,
        // enableDelete: true,
        // showRowNo: true,
        // enableRowNoButton: true,      // Add row no as button. { name: `btnRowNo_${gridName}`, moreData: { gridName, rid } }

        columns: gridColumns,
	},
	editer: {
	//#region grid editor for CustomerAddress
	addressCode: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'addressCode',
		placeholder: 'addressCode',
		maxLength: 50,
		textStyle: {},
	},
	addressType: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'customerAddress',
		name: 'addressType',
		placeholder: 'addressType',
		format: 'number',
		textStyle: {},
	},
	description: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'description',
		placeholder: 'description',
		maxLength: 200,
		textStyle: {},
	},
	name: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'name',
		placeholder: 'name',
		maxLength: 100,
		textStyle: {},
	},
	company: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'company',
		placeholder: 'company',
		maxLength: 100,
		textStyle: {},
	},
	companyJobTitle: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'companyJobTitle',
		placeholder: 'companyJobTitle',
		maxLength: 100,
		textStyle: {},
	},
	attention: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'attention',
		placeholder: 'attention',
		maxLength: 100,
		textStyle: {},
	},
	addressLine1: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'addressLine1',
		placeholder: 'addressLine1',
		maxLength: 200,
		textStyle: {},
	},
	addressLine2: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'addressLine2',
		placeholder: 'addressLine2',
		maxLength: 200,
		textStyle: {},
	},
	city: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'city',
		placeholder: 'city',
		maxLength: 100,
		textStyle: {},
	},
	state: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'state',
		placeholder: 'state',
		maxLength: 50,
		textStyle: {},
	},
	stateFullName: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'stateFullName',
		placeholder: 'stateFullName',
		maxLength: 100,
		textStyle: {},
	},
	postalCode: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'postalCode',
		placeholder: 'postalCode',
		maxLength: 50,
		textStyle: {},
	},
	postalCodeExt: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'postalCodeExt',
		placeholder: 'postalCodeExt',
		maxLength: 50,
		textStyle: {},
	},
	county: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'county',
		placeholder: 'county',
		maxLength: 100,
		textStyle: {},
	},
	country: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'country',
		placeholder: 'country',
		maxLength: 100,
		textStyle: {},
	},
	email: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'email',
		placeholder: 'email',
		maxLength: 100,
		textStyle: {},
	},
	daytimePhone: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'daytimePhone',
		placeholder: 'daytimePhone',
		maxLength: 50,
		textStyle: {},
	},
	nightPhone: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'nightPhone',
		placeholder: 'nightPhone',
		maxLength: 50,
		textStyle: {},
	},
	updateDateUtc: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'customerAddress',
		name: 'updateDateUtc',
		placeholder: 'updateDateUtc',
		format: 'date',
		textStyle: {},
	},
	enterBy: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'enterBy',
		placeholder: 'enterBy',
		maxLength: 100,
		textStyle: {},
	},
	updateBy: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'customerAddress',
		name: 'updateBy',
		placeholder: 'updateBy',
		maxLength: 100,
		textStyle: {},
	},
	//#endregion grid editor for CustomerAddress
	}
};



