import { ScreenType, ProcessMode } from '../../types/enums';
import { DbComponentEnums, Enums } from '../../types';
import { IconNames } from '../../components/icon';
import { btnSave, btnEdit, btnList, btnDelete } from '../default';
import * as util from '../../util';

import { customerAddressGrid } from './customerAddress.grid';
export const customerUi = { 
    page: {
        screenType: ScreenType.PROCESSING,
        screenid: 1001,
        processMode: ProcessMode.LIST,
        processModeList: [Enums.ProcessMode.LIST],
        title: 'Customer',
        subTitle: '',
        readonly: false,
    },
    header: {
        title: 'Customer',
    },
    navbar: {},
    section: {},
    buttonGroup: {},
    buttons: {
        btnSave,
        btnEdit, 
        btnList, 
        btnDelete,
    },
	ui: {
		//#region UI control for Customer
		digit_seller_id: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'digit_seller_id',
			label: 'digit_seller_id',
			placeholder: 'digit_seller_id',
			maxLength: 50,
			textStyle: {},
		},
		customerCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'customerCode',
			label: 'customerCode',
			placeholder: 'customerCode',
			maxLength: 50,
			textStyle: {},
		},
		customerName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'customerName',
			label: 'customerName',
			placeholder: 'customerName',
			maxLength: 200,
			textStyle: {},
		},
		contact: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'contact',
			label: 'contact',
			placeholder: 'contact',
			maxLength: 200,
			textStyle: {},
		},
		contact2: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'contact2',
			label: 'contact2',
			placeholder: 'contact2',
			maxLength: 200,
			textStyle: {},
		},
		contact3: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'contact3',
			label: 'contact3',
			placeholder: 'contact3',
			maxLength: 200,
			textStyle: {},
		},
		phone1: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'phone1',
			label: 'phone1',
			placeholder: 'phone1',
			maxLength: 50,
			textStyle: {},
		},
		phone2: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'phone2',
			label: 'phone2',
			placeholder: 'phone2',
			maxLength: 50,
			textStyle: {},
		},
		phone3: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'phone3',
			label: 'phone3',
			placeholder: 'phone3',
			maxLength: 50,
			textStyle: {},
		},
		phone4: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'phone4',
			label: 'phone4',
			placeholder: 'phone4',
			maxLength: 50,
			textStyle: {},
		},
		email: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'email',
			label: 'email',
			placeholder: 'email',
			maxLength: 200,
			textStyle: {},
		},
		webSite: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'webSite',
			label: 'webSite',
			placeholder: 'webSite',
			maxLength: 200,
			textStyle: {},
		},
		customerType: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'customerType',
			label: 'customerType',
			placeholder: 'customerType',
			format: 'number',
			textStyle: {},
		},
		customerStatus: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'customerStatus',
			label: 'customerStatus',
			placeholder: 'customerStatus',
			format: 'number',
			textStyle: {},
		},
		businessType: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'businessType',
			label: 'businessType',
			placeholder: 'businessType',
			maxLength: 50,
			textStyle: {},
		},
		priceRule: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'priceRule',
			label: 'priceRule',
			placeholder: 'priceRule',
			maxLength: 50,
			textStyle: {},
		},
		firstDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'customer',
			name: 'firstDate',
			label: 'firstDate',
			placeholder: 'firstDate',
			format: 'date',
			textStyle: {},
		},
		currency: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'currency',
			label: 'currency',
			placeholder: 'currency',
			maxLength: 10,
			textStyle: {},
		},
		creditLimit: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'creditLimit',
			label: 'creditLimit',
			placeholder: 'creditLimit',
			format: 'decimalNumber',
			textStyle: {},
		},
		taxRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'taxRate',
			label: 'taxRate',
			placeholder: 'taxRate',
			format: 'taxRate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		discountRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'discountRate',
			label: 'discountRate',
			placeholder: 'discountRate',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		shippingCarrier: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'shippingCarrier',
			label: 'shippingCarrier',
			placeholder: 'shippingCarrier',
			maxLength: 50,
			textStyle: {},
		},
		shippingClass: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'shippingClass',
			label: 'shippingClass',
			placeholder: 'shippingClass',
			maxLength: 50,
			textStyle: {},
		},
		shippingAccount: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'shippingAccount',
			label: 'shippingAccount',
			placeholder: 'shippingAccount',
			maxLength: 50,
			textStyle: {},
		},
		priority: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'priority',
			label: 'priority',
			placeholder: 'priority',
			maxLength: 10,
			textStyle: {},
		},
		area: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'area',
			label: 'area',
			placeholder: 'area',
			maxLength: 20,
			textStyle: {},
		},
		region: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'region',
			label: 'region',
			placeholder: 'region',
			maxLength: 20,
			textStyle: {},
		},
		districtn: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'districtn',
			label: 'districtn',
			placeholder: 'districtn',
			maxLength: 20,
			textStyle: {},
		},
		zone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'zone',
			label: 'zone',
			placeholder: 'zone',
			maxLength: 20,
			textStyle: {},
		},
		taxId: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'taxId',
			label: 'taxId',
			placeholder: 'taxId',
			maxLength: 50,
			textStyle: {},
		},
		resaleLicense: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'resaleLicense',
			label: 'resaleLicense',
			placeholder: 'resaleLicense',
			maxLength: 50,
			textStyle: {},
		},
		classCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'classCode',
			label: 'classCode',
			placeholder: 'classCode',
			maxLength: 50,
			textStyle: {},
		},
		departmentCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'departmentCode',
			label: 'departmentCode',
			placeholder: 'departmentCode',
			maxLength: 50,
			textStyle: {},
		},
		divisionCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'divisionCode',
			label: 'divisionCode',
			placeholder: 'divisionCode',
			maxLength: 50,
			textStyle: {},
		},
		sourceCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'sourceCode',
			label: 'sourceCode',
			placeholder: 'sourceCode',
			maxLength: 50,
			textStyle: {},
		},
		terms: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'terms',
			label: 'terms',
			placeholder: 'terms',
			maxLength: 50,
			textStyle: {},
		},
		termsDays: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'termsDays',
			label: 'termsDays',
			placeholder: 'termsDays',
			format: 'number',
			textStyle: {},
		},
		salesRep: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'salesRep',
			label: 'salesRep',
			placeholder: 'salesRep',
			maxLength: 100,
			textStyle: {},
		},
		salesRep2: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'salesRep2',
			label: 'salesRep2',
			placeholder: 'salesRep2',
			maxLength: 100,
			textStyle: {},
		},
		salesRep3: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'salesRep3',
			label: 'salesRep3',
			placeholder: 'salesRep3',
			maxLength: 100,
			textStyle: {},
		},
		salesRep4: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'salesRep4',
			label: 'salesRep4',
			placeholder: 'salesRep4',
			maxLength: 100,
			textStyle: {},
		},
		commissionRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'commissionRate',
			label: 'commissionRate',
			placeholder: 'commissionRate',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionRate2: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'commissionRate2',
			label: 'commissionRate2',
			placeholder: 'commissionRate2',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionRate3: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'commissionRate3',
			label: 'commissionRate3',
			placeholder: 'commissionRate3',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionRate4: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'customer',
			name: 'commissionRate4',
			label: 'commissionRate4',
			placeholder: 'commissionRate4',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		updateDateUtc: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'customer',
			name: 'updateDateUtc',
			label: 'updateDateUtc',
			placeholder: 'updateDateUtc',
			format: 'date',
			textStyle: {},
		},
		enterBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'enterBy',
			label: 'enterBy',
			placeholder: 'enterBy',
			maxLength: 100,
			textStyle: {},
		},
		updateBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'customer',
			name: 'updateBy',
			label: 'updateBy',
			placeholder: 'updateBy',
			maxLength: 100,
			textStyle: {},
		},
		//#endregion UI control for Customer



		//#region UI control for CustomerAttributes
		//#endregion UI control for CustomerAttributes



	},

    grid: {
		customerAddress: customerAddressGrid,
    },
    modal: {},
    menu: {},
};

