import { ScreenType, ProcessMode } from '../../types/enums';
import { DbComponentEnums, Enums } from '../../types';
import { IconNames } from '../../components/icon';
import { btnSave, btnEdit, btnList, btnDelete } from '../default';
import * as util from '../../util';

import { warehouseTransferItemsGrid } from './warehouseTransferItems.grid';
export const warehouseTransferUi = { 
    page: {
        screenType: ScreenType.PROCESSING,
        screenid: 1001,
        processMode: ProcessMode.LIST,
        processModeList: [Enums.ProcessMode.LIST],
        title: 'WarehouseTransfer',
        subTitle: '',
        readonly: false,
    },
    header: {
        title: 'WarehouseTransfer',
    },
    navbar: {},
    section: {},
    buttonGroup: {},
    buttons: {
        btnSave,
        btnEdit, 
        btnList, 
        btnDelete,
    },
	ui: {
		//#region UI control for WarehouseTransferHeader
		batchNumber: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'batchNumber',
			label: 'batchNumber',
			placeholder: 'batchNumber',
			maxLength: 50,
			textStyle: {},
		},
		warehouseTransferType: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'warehouseTransferHeader',
			name: 'warehouseTransferType',
			label: 'warehouseTransferType',
			placeholder: 'warehouseTransferType',
			format: 'number',
			textStyle: {},
		},
		warehouseTransferStatus: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'warehouseTransferHeader',
			name: 'warehouseTransferStatus',
			label: 'warehouseTransferStatus',
			placeholder: 'warehouseTransferStatus',
			format: 'number',
			textStyle: {},
		},
		transferDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'warehouseTransferHeader',
			name: 'transferDate',
			label: 'transferDate',
			placeholder: 'transferDate',
			format: 'date',
			textStyle: {},
		},
		transferTime: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'transferTime',
			label: 'transferTime',
			placeholder: 'transferTime',
			format: 'time',
			textStyle: {},
		},
		processor: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'processor',
			label: 'processor',
			placeholder: 'processor',
			maxLength: 50,
			textStyle: {},
		},
		receiveDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'warehouseTransferHeader',
			name: 'receiveDate',
			label: 'receiveDate',
			placeholder: 'receiveDate',
			format: 'date',
			textStyle: {},
		},
		receiveTime: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'receiveTime',
			label: 'receiveTime',
			placeholder: 'receiveTime',
			format: 'time',
			textStyle: {},
		},
		receiveProcessor: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'receiveProcessor',
			label: 'receiveProcessor',
			placeholder: 'receiveProcessor',
			maxLength: 50,
			textStyle: {},
		},
		fromWarehouseCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'fromWarehouseCode',
			label: 'fromWarehouseCode',
			placeholder: 'fromWarehouseCode',
			maxLength: 50,
			textStyle: {},
		},
		toWarehouseCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'toWarehouseCode',
			label: 'toWarehouseCode',
			placeholder: 'toWarehouseCode',
			maxLength: 50,
			textStyle: {},
		},
		inTransitToWarehouseCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'inTransitToWarehouseCode',
			label: 'inTransitToWarehouseCode',
			placeholder: 'inTransitToWarehouseCode',
			maxLength: 50,
			textStyle: {},
		},
		referenceType: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'warehouseTransferHeader',
			name: 'referenceType',
			label: 'referenceType',
			placeholder: 'referenceType',
			format: 'number',
			textStyle: {},
		},
		referenceNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'referenceNum',
			label: 'referenceNum',
			placeholder: 'referenceNum',
			maxLength: 50,
			textStyle: {},
		},
		warehouseTransferSourceCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'warehouseTransferSourceCode',
			label: 'warehouseTransferSourceCode',
			placeholder: 'warehouseTransferSourceCode',
			maxLength: 100,
			textStyle: {},
		},
		updateDateUtc: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'warehouseTransferHeader',
			name: 'updateDateUtc',
			label: 'updateDateUtc',
			placeholder: 'updateDateUtc',
			format: 'date',
			textStyle: {},
		},
		enterBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'enterBy',
			label: 'enterBy',
			placeholder: 'enterBy',
			maxLength: 100,
			textStyle: {},
		},
		updateBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'warehouseTransferHeader',
			name: 'updateBy',
			label: 'updateBy',
			placeholder: 'updateBy',
			maxLength: 100,
			textStyle: {},
		},
		//#endregion UI control for WarehouseTransferHeader



	},

    grid: {
		warehouseTransferItems: warehouseTransferItemsGrid,
    },
    modal: {},
    menu: {},
};

