


//-------------------------------------------------------------------------
// This document is generated by T4
// It will overwrite your changes, please keep it as it is
// <copyright company="DigitBridge">
//     Copyright (c) DigitBridge Inc.  All rights reserved.
// </copyright>
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.Data;
using Microsoft.Data.SqlClient;

using Newtonsoft.Json;

using DigitBridge.Base.Utility;
using DigitBridge.CommerceCentral.YoPoco;
using DigitBridge.CommerceCentral.ERPDb;

namespace DigitBridge.CommerceCentral.ERPMdl
{
    /// <summary>
    /// Represents a InventoryLogHelper SQL Helper Static Class.
    /// NOTE: This class is generated from a T4 template Once - you you wanr re-generate it, you need delete cs file and generate again
    /// </summary>
    public static class InventoryLogHelper
    {

        public static List<InventoryLog> QueryInventoryLogByUuid(string logUuid)
        {
            return SqlQuery.Query<InventoryLog>(
                        ERPDb.InventoryLogHelper.SelectAllWhere(
                            sqlWhere: $"WHERE LogUuid = @logUuid ORDER BY RowNum"
                        ),
                        CommandType.Text, new SqlParameter("@logUuid", logUuid)
                        ).ToList();
        }

        public static List<InventoryLog> QueryInventoryLogByBatchNum(long batchNum)
        {
            return SqlQuery.Query<InventoryLog>(
                        ERPDb.InventoryLogHelper.SelectAllWhere(
                            sqlWhere: $"WHERE BatchNum = @batchNum ORDER BY RowNum"
                        ),
                        CommandType.Text, new SqlParameter("@batchNum", batchNum)
                        ).ToList();
        }
    }
}



