import { ScreenType, ProcessMode } from '../../types/enums';
import { DbComponentEnums, Enums } from '../../types';
import { IconNames } from '../../components/icon';
import { btnSave, btnEdit, btnList, btnDelete } from '../default';
import * as util from '../../util';

import { apInvoiceItemsGrid } from './apInvoiceItems.grid';
export const apInvoiceUi = { 
    page: {
        screenType: ScreenType.PROCESSING,
        screenid: 1001,
        processMode: ProcessMode.LIST,
        processModeList: [Enums.ProcessMode.LIST],
        title: 'ApInvoice',
        subTitle: '',
        readonly: false,
    },
    header: {
        title: 'ApInvoice',
    },
    navbar: {},
    section: {},
    buttonGroup: {},
    buttons: {
        btnSave,
        btnEdit, 
        btnList, 
        btnDelete,
    },
	ui: {
		//#region UI control for ApInvoiceHeader
		apInvoiceNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeader',
			name: 'apInvoiceNum',
			label: 'apInvoiceNum',
			placeholder: 'apInvoiceNum',
			maxLength: 50,
			textStyle: {},
		},
		apInvoiceType: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeader',
			name: 'apInvoiceType',
			label: 'apInvoiceType',
			placeholder: 'apInvoiceType',
			format: 'number',
			textStyle: {},
		},
		apInvoiceStatus: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeader',
			name: 'apInvoiceStatus',
			label: 'apInvoiceStatus',
			placeholder: 'apInvoiceStatus',
			format: 'number',
			textStyle: {},
		},
		apInvoiceDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'apInvoiceHeader',
			name: 'apInvoiceDate',
			label: 'apInvoiceDate',
			placeholder: 'apInvoiceDate',
			format: 'date',
			textStyle: {},
		},
		apInvoiceTime: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeader',
			name: 'apInvoiceTime',
			label: 'apInvoiceTime',
			placeholder: 'apInvoiceTime',
			format: 'time',
			textStyle: {},
		},
		vendorNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeader',
			name: 'vendorNum',
			label: 'vendorNum',
			placeholder: 'vendorNum',
			maxLength: 50,
			textStyle: {},
		},
		vendorName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeader',
			name: 'vendorName',
			label: 'vendorName',
			placeholder: 'vendorName',
			maxLength: 100,
			textStyle: {},
		},
		vendorInvoiceNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeader',
			name: 'vendorInvoiceNum',
			label: 'vendorInvoiceNum',
			placeholder: 'vendorInvoiceNum',
			maxLength: 50,
			textStyle: {},
		},
		vendorInvoiceDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'apInvoiceHeader',
			name: 'vendorInvoiceDate',
			label: 'vendorInvoiceDate',
			placeholder: 'vendorInvoiceDate',
			format: 'date',
			textStyle: {},
		},
		dueDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'apInvoiceHeader',
			name: 'dueDate',
			label: 'dueDate',
			placeholder: 'dueDate',
			format: 'date',
			textStyle: {},
		},
		billDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'apInvoiceHeader',
			name: 'billDate',
			label: 'billDate',
			placeholder: 'billDate',
			format: 'date',
			textStyle: {},
		},
		currency: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeader',
			name: 'currency',
			label: 'currency',
			placeholder: 'currency',
			maxLength: 10,
			textStyle: {},
		},
		totalAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeader',
			name: 'totalAmount',
			label: 'totalAmount',
			placeholder: 'totalAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		paidAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeader',
			name: 'paidAmount',
			label: 'paidAmount',
			placeholder: 'paidAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		creditAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeader',
			name: 'creditAmount',
			label: 'creditAmount',
			placeholder: 'creditAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		balance: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeader',
			name: 'balance',
			label: 'balance',
			placeholder: 'balance',
			format: 'decimalNumber',
			textStyle: {},
		},
		creditAccount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeader',
			name: 'creditAccount',
			label: 'creditAccount',
			placeholder: 'creditAccount',
			format: 'number',
			textStyle: {},
		},
		debitAccount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeader',
			name: 'debitAccount',
			label: 'debitAccount',
			placeholder: 'debitAccount',
			format: 'number',
			textStyle: {},
		},
		updateDateUtc: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'apInvoiceHeader',
			name: 'updateDateUtc',
			label: 'updateDateUtc',
			placeholder: 'updateDateUtc',
			format: 'date',
			textStyle: {},
		},
		enterBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeader',
			name: 'enterBy',
			label: 'enterBy',
			placeholder: 'enterBy',
			maxLength: 100,
			textStyle: {},
		},
		updateBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeader',
			name: 'updateBy',
			label: 'updateBy',
			placeholder: 'updateBy',
			maxLength: 100,
			textStyle: {},
		},
		//#endregion UI control for ApInvoiceHeader



		//#region UI control for ApInvoiceHeaderInfo
		centralFulfillmentNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeaderInfo',
			name: 'centralFulfillmentNum',
			label: 'centralFulfillmentNum',
			placeholder: 'centralFulfillmentNum',
			format: 'number',
			textStyle: {},
		},
		shippingCarrier: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'shippingCarrier',
			label: 'shippingCarrier',
			placeholder: 'shippingCarrier',
			maxLength: 50,
			textStyle: {},
		},
		shippingClass: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'shippingClass',
			label: 'shippingClass',
			placeholder: 'shippingClass',
			maxLength: 50,
			textStyle: {},
		},
		centralOrderNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'apInvoiceHeaderInfo',
			name: 'centralOrderNum',
			label: 'centralOrderNum',
			placeholder: 'centralOrderNum',
			format: 'number',
			textStyle: {},
		},
		channelOrderID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'channelOrderID',
			label: 'channelOrderID',
			placeholder: 'channelOrderID',
			maxLength: 130,
			textStyle: {},
		},
		secondaryChannelOrderID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'secondaryChannelOrderID',
			label: 'secondaryChannelOrderID',
			placeholder: 'secondaryChannelOrderID',
			maxLength: 200,
			textStyle: {},
		},
		shippingAccount: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'shippingAccount',
			label: 'shippingAccount',
			placeholder: 'shippingAccount',
			maxLength: 100,
			textStyle: {},
		},
		refNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'refNum',
			label: 'refNum',
			placeholder: 'refNum',
			maxLength: 100,
			textStyle: {},
		},
		customerPoNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'customerPoNum',
			label: 'customerPoNum',
			placeholder: 'customerPoNum',
			maxLength: 100,
			textStyle: {},
		},
		billToName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToName',
			label: 'billToName',
			placeholder: 'billToName',
			maxLength: 100,
			textStyle: {},
		},
		billToCompany: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToCompany',
			label: 'billToCompany',
			placeholder: 'billToCompany',
			maxLength: 100,
			textStyle: {},
		},
		billToAttention: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToAttention',
			label: 'billToAttention',
			placeholder: 'billToAttention',
			maxLength: 100,
			textStyle: {},
		},
		billToAddressLine1: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToAddressLine1',
			label: 'billToAddressLine1',
			placeholder: 'billToAddressLine1',
			maxLength: 200,
			textStyle: {},
		},
		billToAddressLine2: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToAddressLine2',
			label: 'billToAddressLine2',
			placeholder: 'billToAddressLine2',
			maxLength: 200,
			textStyle: {},
		},
		billToCity: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToCity',
			label: 'billToCity',
			placeholder: 'billToCity',
			maxLength: 100,
			textStyle: {},
		},
		billToState: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToState',
			label: 'billToState',
			placeholder: 'billToState',
			maxLength: 50,
			textStyle: {},
		},
		billToStateFullName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToStateFullName',
			label: 'billToStateFullName',
			placeholder: 'billToStateFullName',
			maxLength: 100,
			textStyle: {},
		},
		billToPostalCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToPostalCode',
			label: 'billToPostalCode',
			placeholder: 'billToPostalCode',
			maxLength: 50,
			textStyle: {},
		},
		billToPostalCodeExt: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToPostalCodeExt',
			label: 'billToPostalCodeExt',
			placeholder: 'billToPostalCodeExt',
			maxLength: 50,
			textStyle: {},
		},
		billToCounty: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToCounty',
			label: 'billToCounty',
			placeholder: 'billToCounty',
			maxLength: 50,
			textStyle: {},
		},
		billToCountry: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToCountry',
			label: 'billToCountry',
			placeholder: 'billToCountry',
			maxLength: 100,
			textStyle: {},
		},
		billToEmail: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToEmail',
			label: 'billToEmail',
			placeholder: 'billToEmail',
			maxLength: 100,
			textStyle: {},
		},
		billToDaytimePhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToDaytimePhone',
			label: 'billToDaytimePhone',
			placeholder: 'billToDaytimePhone',
			maxLength: 50,
			textStyle: {},
		},
		billToNightPhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'apInvoiceHeaderInfo',
			name: 'billToNightPhone',
			label: 'billToNightPhone',
			placeholder: 'billToNightPhone',
			maxLength: 50,
			textStyle: {},
		},
		//#endregion UI control for ApInvoiceHeaderInfo



		//#region UI control for ApInvoiceHeaderAttributes
		//#endregion UI control for ApInvoiceHeaderAttributes



	},

    grid: {
		apInvoiceItems: apInvoiceItemsGrid,
    },
    modal: {},
    menu: {},
};

