
              
    

//-------------------------------------------------------------------------
// This document is generated by T4
// It will overwrite your changes, please keep it as it is
// <copyright company="DigitBridge">
//     Copyright (c) DigitBridge Inc.  All rights reserved.
// </copyright>
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.Text;
using Newtonsoft.Json;
using DigitBridge.Base.Utility;
using DigitBridge.CommerceCentral.YoPoco;

namespace DigitBridge.CommerceCentral.ERPDb
{
    /// <summary>
    /// Represents a SalesOrderHeaderInfo SQL Helper Static Class.
    /// NOTE: This class is generated from a T4 template Once - you you wanr re-generate it, you need delete cs file and generate again
    /// </summary>
    public static class SalesOrderHeaderInfoHelper
    {
        public static readonly string TableName = "SalesOrderHeaderInfo";
        public static readonly string TableAllies = "ordi";

        public static string From(string TableAllies = null) => $"FROM {TableName} {TableAllies ?? TableAllies} ";
        public static string InnerJoin(string TableAllies = null) => $"INNER JOIN {TableName} {TableAllies ?? TableAllies} ";
        public static string LeftJoin(string TableAllies = null) => $"LEFT JOIN {TableName} {TableAllies ?? TableAllies} ";

        #region - static SQL fileds statement

        public static string RowNum(string tableAllies = null, string name = null) => $"{tableAllies ?? TableAllies}.RowNum AS {name ?? "RowNum"} ";
        public static string SalesOrderUuid(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.SalesOrderUuid) AS {name ?? "SalesOrderUuid"} ";
        public static string CentralFulfillmentNum(string tableAllies = null, string name = null) => $"{tableAllies ?? TableAllies}.CentralFulfillmentNum AS {name ?? "CentralFulfillmentNum"} ";
        public static string ShippingCarrier(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShippingCarrier) AS {name ?? "ShippingCarrier"} ";
        public static string ShippingClass(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShippingClass) AS {name ?? "ShippingClass"} ";
        public static string DistributionCenterNum(string tableAllies = null, string name = null) => $"{tableAllies ?? TableAllies}.DistributionCenterNum AS {name ?? "DistributionCenterNum"} ";
        public static string CentralOrderNum(string tableAllies = null, string name = null) => $"{tableAllies ?? TableAllies}.CentralOrderNum AS {name ?? "CentralOrderNum"} ";
        public static string ChannelNum(string tableAllies = null, string name = null) => $"{tableAllies ?? TableAllies}.ChannelNum AS {name ?? "ChannelNum"} ";
        public static string ChannelAccountNum(string tableAllies = null, string name = null) => $"{tableAllies ?? TableAllies}.ChannelAccountNum AS {name ?? "ChannelAccountNum"} ";
        public static string ChannelOrderID(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ChannelOrderID) AS {name ?? "ChannelOrderID"} ";
        public static string SecondaryChannelOrderID(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.SecondaryChannelOrderID) AS {name ?? "SecondaryChannelOrderID"} ";
        public static string ShippingAccount(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShippingAccount) AS {name ?? "ShippingAccount"} ";
        public static string WarehouseUuid(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.WarehouseUuid) AS {name ?? "WarehouseUuid"} ";
        public static string WarehouseCode(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.WarehouseCode) AS {name ?? "WarehouseCode"} ";
        public static string RefNum(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.RefNum) AS {name ?? "RefNum"} ";
        public static string CustomerPoNum(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.CustomerPoNum) AS {name ?? "CustomerPoNum"} ";
        public static string EndBuyerUserID(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.EndBuyerUserID) AS {name ?? "EndBuyerUserID"} ";
        public static string EndBuyerName(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.EndBuyerName) AS {name ?? "EndBuyerName"} ";
        public static string EndBuyerEmail(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.EndBuyerEmail) AS {name ?? "EndBuyerEmail"} ";
        public static string ShipToName(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToName) AS {name ?? "ShipToName"} ";
        public static string ShipToFirstName(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToFirstName) AS {name ?? "ShipToFirstName"} ";
        public static string ShipToLastName(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToLastName) AS {name ?? "ShipToLastName"} ";
        public static string ShipToSuffix(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToSuffix) AS {name ?? "ShipToSuffix"} ";
        public static string ShipToCompany(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToCompany) AS {name ?? "ShipToCompany"} ";
        public static string ShipToCompanyJobTitle(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToCompanyJobTitle) AS {name ?? "ShipToCompanyJobTitle"} ";
        public static string ShipToAttention(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToAttention) AS {name ?? "ShipToAttention"} ";
        public static string ShipToAddressLine1(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToAddressLine1) AS {name ?? "ShipToAddressLine1"} ";
        public static string ShipToAddressLine2(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToAddressLine2) AS {name ?? "ShipToAddressLine2"} ";
        public static string ShipToAddressLine3(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToAddressLine3) AS {name ?? "ShipToAddressLine3"} ";
        public static string ShipToCity(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToCity) AS {name ?? "ShipToCity"} ";
        public static string ShipToState(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToState) AS {name ?? "ShipToState"} ";
        public static string ShipToStateFullName(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToStateFullName) AS {name ?? "ShipToStateFullName"} ";
        public static string ShipToPostalCode(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToPostalCode) AS {name ?? "ShipToPostalCode"} ";
        public static string ShipToPostalCodeExt(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToPostalCodeExt) AS {name ?? "ShipToPostalCodeExt"} ";
        public static string ShipToCounty(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToCounty) AS {name ?? "ShipToCounty"} ";
        public static string ShipToCountry(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToCountry) AS {name ?? "ShipToCountry"} ";
        public static string ShipToEmail(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToEmail) AS {name ?? "ShipToEmail"} ";
        public static string ShipToDaytimePhone(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToDaytimePhone) AS {name ?? "ShipToDaytimePhone"} ";
        public static string ShipToNightPhone(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.ShipToNightPhone) AS {name ?? "ShipToNightPhone"} ";
        public static string BillToName(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToName) AS {name ?? "BillToName"} ";
        public static string BillToFirstName(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToFirstName) AS {name ?? "BillToFirstName"} ";
        public static string BillToLastName(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToLastName) AS {name ?? "BillToLastName"} ";
        public static string BillToSuffix(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToSuffix) AS {name ?? "BillToSuffix"} ";
        public static string BillToCompany(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToCompany) AS {name ?? "BillToCompany"} ";
        public static string BillToCompanyJobTitle(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToCompanyJobTitle) AS {name ?? "BillToCompanyJobTitle"} ";
        public static string BillToAttention(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToAttention) AS {name ?? "BillToAttention"} ";
        public static string BillToAddressLine1(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToAddressLine1) AS {name ?? "BillToAddressLine1"} ";
        public static string BillToAddressLine2(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToAddressLine2) AS {name ?? "BillToAddressLine2"} ";
        public static string BillToAddressLine3(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToAddressLine3) AS {name ?? "BillToAddressLine3"} ";
        public static string BillToCity(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToCity) AS {name ?? "BillToCity"} ";
        public static string BillToState(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToState) AS {name ?? "BillToState"} ";
        public static string BillToStateFullName(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToStateFullName) AS {name ?? "BillToStateFullName"} ";
        public static string BillToPostalCode(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToPostalCode) AS {name ?? "BillToPostalCode"} ";
        public static string BillToPostalCodeExt(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToPostalCodeExt) AS {name ?? "BillToPostalCodeExt"} ";
        public static string BillToCounty(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToCounty) AS {name ?? "BillToCounty"} ";
        public static string BillToCountry(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToCountry) AS {name ?? "BillToCountry"} ";
        public static string BillToEmail(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToEmail) AS {name ?? "BillToEmail"} ";
        public static string BillToDaytimePhone(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToDaytimePhone) AS {name ?? "BillToDaytimePhone"} ";
        public static string BillToNightPhone(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.BillToNightPhone) AS {name ?? "BillToNightPhone"} ";
        public static string UpdateDateUtc(string tableAllies = null, string name = null) => $"{tableAllies ?? TableAllies}.UpdateDateUtc AS {name ?? "UpdateDateUtc"} ";
        public static string EnterBy(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.EnterBy) AS {name ?? "EnterBy"} ";
        public static string UpdateBy(string tableAllies = null, string name = null) => $"RTRIM({tableAllies ?? TableAllies}.UpdateBy) AS {name ?? "UpdateBy"} ";
        public static string EnterDateUtc(string tableAllies = null, string name = null) => $"{tableAllies ?? TableAllies}.EnterDateUtc AS {name ?? "EnterDateUtc"} ";
        public static string DigitBridgeGuid(string tableAllies = null, string name = null) => $"{tableAllies ?? TableAllies}.DigitBridgeGuid AS {name ?? "DigitBridgeGuid"} ";

        #endregion - static SQL fileds statement

        public static string SelectAll(string tableAllies = null) 
        {
            var allies = string.IsNullOrEmpty(tableAllies) ? string.Empty : $"{tableAllies.TrimEnd()}.";
            return $@"
{allies}RowNum AS RowNum,
RTRIM({allies}SalesOrderUuid) AS SalesOrderUuid,
{allies}CentralFulfillmentNum AS CentralFulfillmentNum,
RTRIM({allies}ShippingCarrier) AS ShippingCarrier,
RTRIM({allies}ShippingClass) AS ShippingClass,
{allies}DistributionCenterNum AS DistributionCenterNum,
{allies}CentralOrderNum AS CentralOrderNum,
{allies}ChannelNum AS ChannelNum,
{allies}ChannelAccountNum AS ChannelAccountNum,
RTRIM({allies}ChannelOrderID) AS ChannelOrderID,
RTRIM({allies}SecondaryChannelOrderID) AS SecondaryChannelOrderID,
RTRIM({allies}ShippingAccount) AS ShippingAccount,
RTRIM({allies}WarehouseUuid) AS WarehouseUuid,
RTRIM({allies}WarehouseCode) AS WarehouseCode,
RTRIM({allies}RefNum) AS RefNum,
RTRIM({allies}CustomerPoNum) AS CustomerPoNum,
RTRIM({allies}EndBuyerUserID) AS EndBuyerUserID,
RTRIM({allies}EndBuyerName) AS EndBuyerName,
RTRIM({allies}EndBuyerEmail) AS EndBuyerEmail,
RTRIM({allies}ShipToName) AS ShipToName,
RTRIM({allies}ShipToFirstName) AS ShipToFirstName,
RTRIM({allies}ShipToLastName) AS ShipToLastName,
RTRIM({allies}ShipToSuffix) AS ShipToSuffix,
RTRIM({allies}ShipToCompany) AS ShipToCompany,
RTRIM({allies}ShipToCompanyJobTitle) AS ShipToCompanyJobTitle,
RTRIM({allies}ShipToAttention) AS ShipToAttention,
RTRIM({allies}ShipToAddressLine1) AS ShipToAddressLine1,
RTRIM({allies}ShipToAddressLine2) AS ShipToAddressLine2,
RTRIM({allies}ShipToAddressLine3) AS ShipToAddressLine3,
RTRIM({allies}ShipToCity) AS ShipToCity,
RTRIM({allies}ShipToState) AS ShipToState,
RTRIM({allies}ShipToStateFullName) AS ShipToStateFullName,
RTRIM({allies}ShipToPostalCode) AS ShipToPostalCode,
RTRIM({allies}ShipToPostalCodeExt) AS ShipToPostalCodeExt,
RTRIM({allies}ShipToCounty) AS ShipToCounty,
RTRIM({allies}ShipToCountry) AS ShipToCountry,
RTRIM({allies}ShipToEmail) AS ShipToEmail,
RTRIM({allies}ShipToDaytimePhone) AS ShipToDaytimePhone,
RTRIM({allies}ShipToNightPhone) AS ShipToNightPhone,
RTRIM({allies}BillToName) AS BillToName,
RTRIM({allies}BillToFirstName) AS BillToFirstName,
RTRIM({allies}BillToLastName) AS BillToLastName,
RTRIM({allies}BillToSuffix) AS BillToSuffix,
RTRIM({allies}BillToCompany) AS BillToCompany,
RTRIM({allies}BillToCompanyJobTitle) AS BillToCompanyJobTitle,
RTRIM({allies}BillToAttention) AS BillToAttention,
RTRIM({allies}BillToAddressLine1) AS BillToAddressLine1,
RTRIM({allies}BillToAddressLine2) AS BillToAddressLine2,
RTRIM({allies}BillToAddressLine3) AS BillToAddressLine3,
RTRIM({allies}BillToCity) AS BillToCity,
RTRIM({allies}BillToState) AS BillToState,
RTRIM({allies}BillToStateFullName) AS BillToStateFullName,
RTRIM({allies}BillToPostalCode) AS BillToPostalCode,
RTRIM({allies}BillToPostalCodeExt) AS BillToPostalCodeExt,
RTRIM({allies}BillToCounty) AS BillToCounty,
RTRIM({allies}BillToCountry) AS BillToCountry,
RTRIM({allies}BillToEmail) AS BillToEmail,
RTRIM({allies}BillToDaytimePhone) AS BillToDaytimePhone,
RTRIM({allies}BillToNightPhone) AS BillToNightPhone,
{allies}UpdateDateUtc AS UpdateDateUtc,
RTRIM({allies}EnterBy) AS EnterBy,
RTRIM({allies}UpdateBy) AS UpdateBy,
{allies}EnterDateUtc AS EnterDateUtc,
{allies}DigitBridgeGuid AS DigitBridgeGuid
";
        }

        public static string SelectAllWhere(string sqlWhere, string tableAllies = null, bool forJson = false) 
        {
            if (!sqlWhere.StartsWith("WHERE", StringComparison.CurrentCultureIgnoreCase))
                sqlWhere = $"WHERE {sqlWhere}";
            var forJsonString = forJson ? "FOR JSON PATH" : string.Empty;
            var allies = string.IsNullOrEmpty(tableAllies) ? string.Empty : tableAllies.TrimEnd();

            return $"SELECT {SelectAll(tableAllies)} FROM {TableName} {allies} {sqlWhere} {forJsonString}";
        }

    }
}

