              
    

//-------------------------------------------------------------------------
// This document is generated by T4
// It will overwrite your changes, please keep it as it is
// <copyright company="DigitBridge">
//     Copyright (c) DigitBridge Inc.  All rights reserved.
// </copyright>
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using System.Data;
using Microsoft.Extensions.Configuration;
using Microsoft.Data.SqlClient;
using Xunit;
using DigitBridge.CommerceCentral.YoPoco;
using DigitBridge.Base.Utility;
using DigitBridge.CommerceCentral.XUnit.Common;
using Bogus;

namespace DigitBridge.CommerceCentral.ERPDb.Tests.Integration
{
    /// <summary>
    /// Represents a Tester for ActivityLog.
    /// NOTE: This class is generated from a T4 template - you should not modify it manually.
    /// </summary>
    public partial class ActivityLogTests : IDisposable, IClassFixture<TestFixture<StartupTest>>
    {
        public static Faker<ActivityLog> GetFakerData()
        {
            #region faker data rules
            return new Faker<ActivityLog>()
					.RuleFor(u => u.DatabaseNum, f => f.Random.Int(1, 100))
					.RuleFor(u => u.MasterAccountNum, f => f.Random.Int(1, 100))
					.RuleFor(u => u.ProfileNum, f => f.Random.Int(1, 100))
					.RuleFor(u => u.LogUuid, f => f.Random.Guid().ToString())
					.RuleFor(u => u.LogDate, f => f.Date.Past(0).Date)
					.RuleFor(u => u.Type, f => f.Random.Int(1, 100))
					.RuleFor(u => u.Action, f => f.Random.Int(1, 100))
					.RuleFor(u => u.ProcessUuid, f => f.Random.Guid().ToString())
					.RuleFor(u => u.ProcessNumber, f => f.Random.AlphaNumeric(50))
					.RuleFor(u => u.LogMessage, f => f.Lorem.Sentence())
					.RuleFor(u => u.LogSource, f => f.Lorem.Sentence().TruncateTo(200))
					.RuleFor(u => u.UpdateDateUtc, f => f.Date.Past(0).Date)
					.RuleFor(u => u.EnterBy, f => f.Lorem.Sentence().TruncateTo(100))
					.RuleFor(u => u.UpdateBy, f => f.Lorem.Sentence().TruncateTo(100))
					;
            #endregion faker data rules
        }

        protected const string SkipReason = "Debug Helper Function";

        protected TestFixture<StartupTest> Fixture { get; }
        public IConfiguration Configuration { get; }
        public Faker<ActivityLog> FakerData { get; set; }
        public IDataBaseFactory DataBaseFactory { get; set; }

        public ActivityLogTests(TestFixture<StartupTest> fixture) 
        {
            Fixture = fixture;
            Configuration = fixture.Configuration;

            InitForTest();
        }
        protected void InitForTest()
        {
            var Seq = 0;
            DataBaseFactory = new DataBaseFactory(Configuration["dsn"]);
            FakerData = GetFakerData();
        }
        public void Dispose()
        {
        }

        //[Fact()]
        [Fact(Skip = SkipReason)]
        public void Register_Test()
        {
            var data = FakerData.Generate();
            data.Register();
            var poco = data.GetPocoData();

            Assert.True(true, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void CopyFrom_Test()
        {
            var data = FakerData.Generate();
            var dataJson = data.ObjectToString();
            var newData = FakerData.Generate();
            var newDataJson = newData.ObjectToString();
            data?.CopyFrom(newData);
            var result = !data.Equals(newData);

			Assert.True(true, "This is a generated tester, please report any tester bug to team leader.");
        }

        #region sync methods

        [Fact()]
		//[Fact(Skip = SkipReason)]
		public void Add_Test()
		{
			var data = FakerData.Generate();
            data.SetDataBaseFactory(DataBaseFactory);
            DataBaseFactory.Begin();
			data.Add();
            DataBaseFactory.Commit();

            var dataGet = DataBaseFactory.GetFromCacheById<ActivityLog>(data.UniqueId);
            var result = data.Equals(dataGet);

			Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
		}

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void Put_Test()
        {
            var list = DataBaseFactory.Find<ActivityLog>("SELECT TOP 1 * FROM ActivityLog").ToList();

            DataBaseFactory.Begin();
            var data = list.FirstOrDefault();
            data.SetDataBaseFactory(DataBaseFactory);
            var newData = FakerData.Generate();
            data?.CopyFrom(newData);
            data.Put();
            DataBaseFactory.Commit();

            var dataGet = DataBaseFactory.GetFromCacheById<ActivityLog>(data.UniqueId);
            var result = data.Equals(dataGet);

			Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void Patch_Test()
        {
            var list = DataBaseFactory.Find<ActivityLog>("SELECT TOP 1 * FROM ActivityLog").ToList();

            DataBaseFactory.Begin();
            var data = list.FirstOrDefault();
            var dataOrig = new ActivityLog();
            dataOrig?.CopyFrom(data);

            data.SetDataBaseFactory(DataBaseFactory);
            var newData = FakerData.Generate();
            data?.CopyFrom(newData);
            data.Patch(new[] { "ProcessNumber", "LogMessage" });
            DataBaseFactory.Commit();

            var dataGet = DataBaseFactory.GetFromCache<ActivityLog>(data.RowNum);
            var result = dataGet.ProcessNumber != dataOrig.ProcessNumber &&
                            dataGet.LogMessage != dataOrig.LogMessage &&
                            dataGet.ProcessNumber == newData.ProcessNumber &&
                            dataGet.LogMessage == newData.LogMessage;

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void Save_Test()
        {
	        var dataNew = FakerData.Generate();
            dataNew.SetDataBaseFactory(DataBaseFactory);
            DataBaseFactory.Begin();
            dataNew.Save();
            DataBaseFactory.Commit();

            var dataUpdate = DataBaseFactory.GetById<ActivityLog>(dataNew.UniqueId);
			var dataChanged = FakerData.Generate();
            dataUpdate?.CopyFrom(dataChanged, new[] {"LogUuid"});

            DataBaseFactory.Begin();
            dataUpdate.Save();
            DataBaseFactory.Commit();

            var dataGet = DataBaseFactory.GetFromCacheById<ActivityLog>(dataUpdate.UniqueId);
            var result = dataUpdate.Equals(dataGet);

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void Delete_Test()
        { 
            var list = DataBaseFactory.Find<ActivityLog>("SELECT TOP 1 * FROM ActivityLog").ToList();
            var data = list.FirstOrDefault();

            DataBaseFactory.Begin();
            data.SetDataBaseFactory(DataBaseFactory);
            data.Delete();
            DataBaseFactory.Commit();

            var result = DataBaseFactory.ExistUniqueId<ActivityLog>(data.UniqueId);

            Assert.True(!result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void Get_Test()
        {
            //var list = DataBaseFactory.Find<ActivityLog>().ToList();
            //var listData = list.FirstOrDefault();
            //var data = DataBaseFactory.Get<ActivityLog>(listData.RowNum);
            //var result = data.Equals(listData);

            var list = DataBaseFactory.Find<ActivityLog>("SELECT TOP 1 * FROM ActivityLog").ToList();
            var listData = list.FirstOrDefault(); 
            var result = listData!=null;

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void GetById_Test()
        {
            var list = DataBaseFactory.Find<ActivityLog>("SELECT TOP 1 * FROM ActivityLog").ToList();
            var listData = list.FirstOrDefault();
            var data = DataBaseFactory.GetById<ActivityLog>(listData.UniqueId);
            var result = data.Equals(listData);

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void AddList_Test()
        {
            var list = FakerData.Generate(10);
            var ProcessUuid = Guid.NewGuid().ToString();

            list.ForEach(x => x.ProcessUuid = ProcessUuid);
            list.SetDataBaseFactory<ActivityLog>(DataBaseFactory)
                .Save<ActivityLog>();

            var cnt = DataBaseFactory.Count<ActivityLog>("WHERE ProcessUuid = @0", ProcessUuid);
            var result = cnt.Equals(list.Count());

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void SaveList_Test()
        {
            var list = FakerData.Generate(10);
            var ProcessUuid = Guid.NewGuid().ToString();

            list.ForEach(x => x.ProcessUuid = ProcessUuid);
            list.SetDataBaseFactory<ActivityLog>(DataBaseFactory)
                .Save<ActivityLog>();

            var NewLogMessage = Guid.NewGuid().ToString();
            var listFind = DataBaseFactory.Find<ActivityLog>("WHERE ProcessUuid = @0 ORDER BY RowNum", ProcessUuid).ToList();
            listFind.ToList().ForEach(x => x.LogMessage = NewLogMessage);
            listFind.Save<ActivityLog>();

            list = DataBaseFactory.Find<ActivityLog>("WHERE ProcessUuid = @0 ORDER BY RowNum", ProcessUuid).ToList();
            var result = list.Where(x => x.LogMessage == NewLogMessage).Count() == listFind.Count();

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void DeleteList_Test()
        {
            var list = FakerData.Generate(10);
            var ProcessUuid = Guid.NewGuid().ToString();

            list.ForEach(x => x.ProcessUuid = ProcessUuid);
            list.SetDataBaseFactory<ActivityLog>(DataBaseFactory)
                .Save();

            var listFind = DataBaseFactory.Find<ActivityLog>("WHERE ProcessUuid = @0 ORDER BY RowNum", ProcessUuid).ToList();
            listFind.Delete();

            var cnt = DataBaseFactory.Count<ActivityLog>("WHERE ProcessUuid = @0", ProcessUuid);
            var result = cnt == 0;

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public void GetFromCacheById_Test()
        {
            var list = DataBaseFactory.Find<ActivityLog>("SELECT TOP 1 * FROM ActivityLog").ToList();
            var data = list.FirstOrDefault();
            var data1 = DataBaseFactory.GetFromCacheById<ActivityLog>(data.UniqueId);
            var data2 = DataBaseFactory.GetFromCacheById<ActivityLog>(data.UniqueId);

            var result = data1 == data2;

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        #endregion sync methods

        #region async methods

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task AddAsync_Test()
        {
            var data = FakerData.Generate();
            data.SetDataBaseFactory(DataBaseFactory);
            DataBaseFactory.Begin();
            await data.AddAsync();
            DataBaseFactory.Commit();

            var dataGet = await DataBaseFactory.GetFromCacheByIdAsync<ActivityLog>(data.UniqueId);
            var result = data.Equals(dataGet);

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task PutAsync_Test()
        {
            var list = (await DataBaseFactory.FindAsync<ActivityLog>()).ToList();

            DataBaseFactory.Begin();
            var data = list.FirstOrDefault();
            data.SetDataBaseFactory(DataBaseFactory);
            var newData = FakerData.Generate();
            data?.CopyFrom(newData);
            await data.PutAsync();
            DataBaseFactory.Commit();

            var dataGet = await DataBaseFactory.GetFromCacheByIdAsync<ActivityLog>(data.UniqueId);
            var result = data.Equals(dataGet);

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task PatchAsync_Test()
        {
            var list = (await DataBaseFactory.FindAsync<ActivityLog>()).ToList();

            DataBaseFactory.Begin();
            var data = list.FirstOrDefault();
            var dataOrig = new ActivityLog();
            dataOrig?.CopyFrom(data);

            data.SetDataBaseFactory(DataBaseFactory);
            var newData = FakerData.Generate();
            data?.CopyFrom(newData);
            await data.PatchAsync(new[] { "ProcessNumber", "LogMessage" });
            DataBaseFactory.Commit();

            var dataGet = await DataBaseFactory.GetFromCacheAsync<ActivityLog>(data.RowNum);
            var result = dataGet.ProcessNumber != dataOrig.ProcessNumber &&
                            dataGet.LogMessage != dataOrig.LogMessage &&
                            dataGet.ProcessNumber == newData.ProcessNumber &&
                            dataGet.LogMessage == newData.LogMessage;

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task SaveAsync_Test()
        {
            var dataNew = FakerData.Generate();
            dataNew.SetDataBaseFactory(DataBaseFactory);
            DataBaseFactory.Begin();
            await dataNew.SaveAsync();
            DataBaseFactory.Commit();

            var dataUpdate = await DataBaseFactory.GetByIdAsync<ActivityLog>(dataNew.UniqueId);
            var dataChanged = FakerData.Generate();
            dataUpdate?.CopyFrom(dataChanged, new[] { "LogUuid" });

            DataBaseFactory.Begin();
            await dataUpdate.SaveAsync();
            DataBaseFactory.Commit();

            var dataGet = await DataBaseFactory.GetFromCacheByIdAsync<ActivityLog>(dataUpdate.UniqueId);
            var result = dataUpdate.Equals(dataGet);

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task DeleteAsync_Test()
        {
            var list = (await DataBaseFactory.FindAsync<ActivityLog>()).ToList();
            var data = list.FirstOrDefault();

            DataBaseFactory.Begin();
            data.SetDataBaseFactory(DataBaseFactory);
            await data.DeleteAsync();
            DataBaseFactory.Commit();

            var result = await DataBaseFactory.ExistUniqueIdAsync<ActivityLog>(data.UniqueId);

            Assert.True(!result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task GetAsync_Test()
        {
            var list = (await DataBaseFactory.FindAsync<ActivityLog>()).ToList();
            var listData = list.FirstOrDefault();
            var data = await DataBaseFactory.GetAsync<ActivityLog>(listData.RowNum);
            var result = data.Equals(listData);

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task GetByIdAsync_Test()
        {
            var list = (await DataBaseFactory.FindAsync<ActivityLog>()).ToList();
            var listData = list.FirstOrDefault();
            var data = await DataBaseFactory.GetByIdAsync<ActivityLog>(listData.UniqueId);
            var result = data.Equals(listData);

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task AddListAsync_Test()
        {
            var list = FakerData.Generate(10);
            var ProcessUuid = Guid.NewGuid().ToString();

            list.ForEach(x => x.ProcessUuid = ProcessUuid);
            await list
                .SetDataBaseFactory<ActivityLog>(DataBaseFactory)
                .SaveAsync<ActivityLog>();

            var cnt = await DataBaseFactory.CountAsync<ActivityLog>("WHERE ProcessUuid = @0", ProcessUuid);
            var result = cnt.Equals(list.Count());

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task SaveListAsync_Test()
        {
            var list = FakerData.Generate(10);
            var ProcessUuid = Guid.NewGuid().ToString();

            list.ForEach(x => x.ProcessUuid = ProcessUuid);
            await list
                .SetDataBaseFactory<ActivityLog>(DataBaseFactory)
                .SaveAsync<ActivityLog>();

            var NewLogMessage = Guid.NewGuid().ToString();
            var listFind = (await DataBaseFactory.FindAsync<ActivityLog>("WHERE ProcessUuid = @0 ORDER BY RowNum", ProcessUuid)).ToList();
            listFind.ToList().ForEach(x => x.LogMessage = NewLogMessage);
            await listFind.SaveAsync<ActivityLog>();

            list = DataBaseFactory.Find<ActivityLog>("WHERE ProcessUuid = @0 ORDER BY RowNum", ProcessUuid).ToList();
            var result = list.Where(x => x.LogMessage == NewLogMessage).Count() == listFind.Count();

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task DeleteListAsync_Test()
        {
            var list = FakerData.Generate(10);
            var ProcessUuid = Guid.NewGuid().ToString();

            list.ForEach(x => x.ProcessUuid = ProcessUuid);
            await list
                .SetDataBaseFactory<ActivityLog>(DataBaseFactory)
                .SaveAsync();

            var listFind = (await DataBaseFactory.FindAsync<ActivityLog>("WHERE ProcessUuid = @0 ORDER BY RowNum", ProcessUuid)).ToList();
            await listFind.DeleteAsync();

            var cnt = await DataBaseFactory.CountAsync<ActivityLog>("WHERE ProcessUuid = @0", ProcessUuid);
            var result = cnt == 0;

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        [Fact()]
        //[Fact(Skip = SkipReason)]
        public async Task GetFromCacheByIdAsync_Test()
        {
            var list = (await DataBaseFactory.FindAsync<ActivityLog>("SELECT TOP 1 * FROM ActivityLog")).ToList();
            var data = list.FirstOrDefault();
            var data1 = await DataBaseFactory.GetFromCacheByIdAsync<ActivityLog>(data.UniqueId);
            var data2 = await DataBaseFactory.GetFromCacheByIdAsync<ActivityLog>(data.UniqueId);

            var result = data1 == data2;

            Assert.True(result, "This is a generated tester, please report any tester bug to team leader.");
        }

        #endregion sync methods

    }
}


