
              
    

//-------------------------------------------------------------------------
// This document is generated by T4
// It will only generate once, if you want re-generate it, you need delete this file first.
// <copyright company="DigitBridge">
//     Copyright (c) DigitBridge Inc.  All rights reserved.
// </copyright>
//-------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using System.Xml.Serialization;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using DigitBridge.CommerceCentral.YoPoco;

namespace DigitBridge.CommerceCentral.ERPDb
{
    /// <summary>
    /// Represents a OrderLine Dto Class.
    /// NOTE: This class is generated from a T4 template Once - you you wanr re-generate it, you need delete cs file and generate again
    /// </summary>
    public class OrderLineDto
    {
        public long? RowNum { get; set; }
        public string UniqueId { get; set; }
        public DateTime? EnterDateUtc { get; set; }
        public Guid DigitBridgeGuid { get; set; }

        #region Properties - Generated 

        public long? CentralOrderLineNum { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasCentralOrderLineNum => CentralOrderLineNum != null;

        public int? DatabaseNum { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasDatabaseNum => DatabaseNum != null;

        public long? CentralOrderNum { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasCentralOrderNum => CentralOrderNum != null;

        public int? MasterAccountNum { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasMasterAccountNum => MasterAccountNum != null;

        public int? ProfileNum { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasProfileNum => ProfileNum != null;

        public int? ChannelNum { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasChannelNum => ChannelNum != null;

        public int? ChannelAccountNum { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasChannelAccountNum => ChannelAccountNum != null;

        [StringLength(130, ErrorMessage = "The ChannelOrderID value cannot exceed 130 characters. ")]
        public string ChannelOrderID { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasChannelOrderID => ChannelOrderID != null;

        public long? CentralProductNum { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasCentralProductNum => CentralProductNum != null;

        [StringLength(50, ErrorMessage = "The ChannelItemID value cannot exceed 50 characters. ")]
        public string ChannelItemID { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasChannelItemID => ChannelItemID != null;

        [StringLength(100, ErrorMessage = "The SKU value cannot exceed 100 characters. ")]
        public string SKU { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasSKU => SKU != null;

        [StringLength(200, ErrorMessage = "The ItemTitle value cannot exceed 200 characters. ")]
        public string ItemTitle { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasItemTitle => ItemTitle != null;

        public decimal? OrderQty { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasOrderQty => OrderQty != null;

        public decimal? UnitPrice { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasUnitPrice => UnitPrice != null;

        public decimal? LineItemTaxAmount { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineItemTaxAmount => LineItemTaxAmount != null;

        public decimal? LineShippingAmount { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineShippingAmount => LineShippingAmount != null;

        public decimal? LineShippingTaxAmount { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineShippingTaxAmount => LineShippingTaxAmount != null;

        public decimal? LineShippingDiscount { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineShippingDiscount => LineShippingDiscount != null;

        public decimal? LineShippingDiscountTaxAmount { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineShippingDiscountTaxAmount => LineShippingDiscountTaxAmount != null;

        public decimal? LineRecyclingFee { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineRecyclingFee => LineRecyclingFee != null;

        [StringLength(500, ErrorMessage = "The LineGiftMsg value cannot exceed 500 characters. ")]
        public string LineGiftMsg { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineGiftMsg => LineGiftMsg != null;

        [StringLength(400, ErrorMessage = "The LineGiftNotes value cannot exceed 400 characters. ")]
        public string LineGiftNotes { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineGiftNotes => LineGiftNotes != null;

        public decimal? LineGiftAmount { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineGiftAmount => LineGiftAmount != null;

        public decimal? LineGiftTaxAmount { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLineGiftTaxAmount => LineGiftTaxAmount != null;

        [StringLength(500, ErrorMessage = "The LinePromotionCodes value cannot exceed 500 characters. ")]
        public string LinePromotionCodes { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLinePromotionCodes => LinePromotionCodes != null;

        public decimal? LinePromotionAmount { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLinePromotionAmount => LinePromotionAmount != null;

        public decimal? LinePromotionTaxAmount { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasLinePromotionTaxAmount => LinePromotionTaxAmount != null;

        public bool? BundleStatus { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasBundleStatus => BundleStatus != null;

        [StringLength(20, ErrorMessage = "The HarmonizedCode value cannot exceed 20 characters. ")]
        public string HarmonizedCode { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasHarmonizedCode => HarmonizedCode != null;

        [StringLength(20, ErrorMessage = "The UPC value cannot exceed 20 characters. ")]
        public string UPC { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasUPC => UPC != null;

        [StringLength(20, ErrorMessage = "The EAN value cannot exceed 20 characters. ")]
        public string EAN { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasEAN => EAN != null;

        [StringLength(20, ErrorMessage = "The UnitOfMeasure value cannot exceed 20 characters. ")]
        public string UnitOfMeasure { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasUnitOfMeasure => UnitOfMeasure != null;

        [StringLength(50, ErrorMessage = "The DBChannelOrderLineRowID value cannot exceed 50 characters. ")]
        public string DBChannelOrderLineRowID { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasDBChannelOrderLineRowID => DBChannelOrderLineRowID != null;

        [StringLength(50, ErrorMessage = "The CentralOrderUuid value cannot exceed 50 characters. ")]
        public string CentralOrderUuid { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasCentralOrderUuid => CentralOrderUuid != null;

        [StringLength(50, ErrorMessage = "The CentralOrderLineUuid value cannot exceed 50 characters. ")]
        public string CentralOrderLineUuid { get; set; }
        [XmlIgnore, JsonIgnore, IgnoreCompare]
        public bool HasCentralOrderLineUuid => CentralOrderLineUuid != null;



        #endregion Properties - Generated 

        #region Children - Generated 

        #endregion Children - Generated 

    }
}



