import { DbComponentEnums } from '../../types';
import { IconNames } from '../../components/icon';
import * as util from '../../util';

//#region all grid columns for InventoryUpdateItems
/** copy column's define object to gridColumns will display column in screen.
const allColumns = [
	{
		id: 'rid',
		name: 'rid',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.hiden,
		defaultFlex: 1,
		systemHide: true,
	},
	{
		id: 'rno',
		name: 'rno',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.rowNo,
		header: '#',
		align: DbComponentEnums.alignEnum.center,
		defaultFlex: 1,
		textStyle: {},
		sortable: false,
		hide: true,
	},
	{
		id: 'seq',
		name: 'seq',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'seq',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'itemDate',
		name: 'itemDate',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'itemDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'itemTime',
		name: 'itemTime',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'itemTime',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		format: 'time',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'sku',
		name: 'sku',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'sku',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'warehouseCode',
		name: 'warehouseCode',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'warehouseCode',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'lotNum',
		name: 'lotNum',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'lotNum',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'description',
		name: 'description',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'description',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'notes',
		name: 'notes',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'notes',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'uom',
		name: 'uom',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'uom',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packType',
		name: 'packType',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packType',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packQty',
		name: 'packQty',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updatePack',
		name: 'updatePack',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updatePack',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'countPack',
		name: 'countPack',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'countPack',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'beforeInstockPack',
		name: 'beforeInstockPack',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'beforeInstockPack',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updateQty',
		name: 'updateQty',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updateQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'countQty',
		name: 'countQty',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'countQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'beforeInstockQty',
		name: 'beforeInstockQty',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'beforeInstockQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'unitCost',
		name: 'unitCost',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'unitCost',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'cost',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'avgCost',
		name: 'avgCost',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'avgCost',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'cost',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'lotCost',
		name: 'lotCost',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'lotCost',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'cost',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'lotInDate',
		name: 'lotInDate',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'lotInDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'lotExpDate',
		name: 'lotExpDate',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'lotExpDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updateDateUtc',
		name: 'updateDateUtc',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updateDateUtc',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'enterBy',
		name: 'enterBy',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'enterBy',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updateBy',
		name: 'updateBy',
		parentName: 'inventoryUpdateItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updateBy',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
];
*/
//#endregion all grid columns for InventoryUpdateItems
// display columns in screen grid
const gridColumns: any[] = [
];

export const inventoryUpdateItemsGrid = { 
	grid: {
        name: 'inventoryUpdateItems',
	    idProperty: 'rid',
        // className: '',
        // bgColor: '',
        // color: '',
        // width: '100%',
        // minWidth: null,
        height: 500,
        // minHeight: 500,

        // hide: false,
        // systemHide?: false,
        // readOnly?: false,
        // reverseScreenReadOnly?: false,
        // disabled?: false,

        // enableEip: true,
        // enableSort: true,
        // enableSelect: true,
        // enableInsert: true,
        // enableDelete: true,
        // showRowNo: true,
        // enableRowNoButton: true,      // Add row no as button. { name: `btnRowNo_${gridName}`, moreData: { gridName, rid } }

        columns: gridColumns,
	},
	editor: {
	//#region grid editor for InventoryUpdateItems
	seq: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'seq',
		placeholder: 'seq',
		format: 'number',
		textStyle: {},
	},
	itemDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'inventoryUpdateItems',
		name: 'itemDate',
		placeholder: 'itemDate',
		format: 'date',
		textStyle: {},
	},
	itemTime: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'itemTime',
		placeholder: 'itemTime',
		format: 'time',
		textStyle: {},
	},
	sku: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'sku',
		placeholder: 'sku',
		maxLength: 100,
		textStyle: {},
	},
	warehouseCode: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'warehouseCode',
		placeholder: 'warehouseCode',
		maxLength: 50,
		textStyle: {},
	},
	lotNum: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'lotNum',
		placeholder: 'lotNum',
		maxLength: 100,
		textStyle: {},
	},
	description: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'description',
		placeholder: 'description',
		maxLength: 200,
		textStyle: {},
	},
	notes: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'notes',
		placeholder: 'notes',
		maxLength: 500,
		textStyle: {},
	},
	uom: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'uom',
		placeholder: 'uom',
		maxLength: 50,
		textStyle: {},
	},
	packType: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'packType',
		placeholder: 'packType',
		maxLength: 50,
		textStyle: {},
	},
	packQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'packQty',
		placeholder: 'packQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	updatePack: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'updatePack',
		placeholder: 'updatePack',
		format: 'decimalNumber',
		textStyle: {},
	},
	countPack: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'countPack',
		placeholder: 'countPack',
		format: 'decimalNumber',
		textStyle: {},
	},
	beforeInstockPack: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'beforeInstockPack',
		placeholder: 'beforeInstockPack',
		format: 'decimalNumber',
		textStyle: {},
	},
	updateQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'updateQty',
		placeholder: 'updateQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	countQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'countQty',
		placeholder: 'countQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	beforeInstockQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'beforeInstockQty',
		placeholder: 'beforeInstockQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	unitCost: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'unitCost',
		placeholder: 'unitCost',
		format: 'cost',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	avgCost: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'avgCost',
		placeholder: 'avgCost',
		format: 'cost',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	lotCost: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'inventoryUpdateItems',
		name: 'lotCost',
		placeholder: 'lotCost',
		format: 'cost',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	lotInDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'inventoryUpdateItems',
		name: 'lotInDate',
		placeholder: 'lotInDate',
		format: 'date',
		textStyle: {},
	},
	lotExpDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'inventoryUpdateItems',
		name: 'lotExpDate',
		placeholder: 'lotExpDate',
		format: 'date',
		textStyle: {},
	},
	updateDateUtc: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'inventoryUpdateItems',
		name: 'updateDateUtc',
		placeholder: 'updateDateUtc',
		format: 'date',
		textStyle: {},
	},
	enterBy: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'enterBy',
		placeholder: 'enterBy',
		maxLength: 100,
		textStyle: {},
	},
	updateBy: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'inventoryUpdateItems',
		name: 'updateBy',
		placeholder: 'updateBy',
		maxLength: 100,
		textStyle: {},
	},
	//#endregion grid editor for InventoryUpdateItems
	}
};



