import { DbComponentEnums } from '../../types';
import { IconNames } from '../../components/icon';
import * as util from '../../util';

//#region all grid columns for PoItems
/** copy column's define object to gridColumns will display column in screen.
const allColumns = [
	{
		id: 'rid',
		name: 'rid',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.hiden,
		defaultFlex: 1,
		systemHide: true,
	},
	{
		id: 'rno',
		name: 'rno',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.rowNo,
		header: '#',
		align: DbComponentEnums.alignEnum.center,
		defaultFlex: 1,
		textStyle: {},
		sortable: false,
		hide: true,
	},
	{
		id: 'seq',
		name: 'seq',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'seq',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'poItemType',
		name: 'poItemType',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'poItemType',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'poItemStatus',
		name: 'poItemStatus',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'poItemStatus',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'poDate',
		name: 'poDate',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'poDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'poTime',
		name: 'poTime',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'poTime',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		format: 'time',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'etaShipDate',
		name: 'etaShipDate',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'etaShipDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'etaArrivalDate',
		name: 'etaArrivalDate',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'etaArrivalDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'cancelDate',
		name: 'cancelDate',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'cancelDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'sku',
		name: 'sku',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'sku',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'description',
		name: 'description',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'description',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'notes',
		name: 'notes',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'notes',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'itemTotalAmount',
		name: 'itemTotalAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'itemTotalAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'currency',
		name: 'currency',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'currency',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'poQty',
		name: 'poQty',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'poQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'receivedQty',
		name: 'receivedQty',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'receivedQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'cancelledQty',
		name: 'cancelledQty',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'cancelledQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'priceRule',
		name: 'priceRule',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'priceRule',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'price',
		name: 'price',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'price',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'price',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'extAmount',
		name: 'extAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'extAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'taxRate',
		name: 'taxRate',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'taxRate',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'taxRate',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'taxAmount',
		name: 'taxAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'taxAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'discountPrice',
		name: 'discountPrice',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'discountPrice',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'price',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'discountRate',
		name: 'discountRate',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'discountRate',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'rate',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'discountAmount',
		name: 'discountAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'discountAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'shippingAmount',
		name: 'shippingAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'shippingAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'shippingTaxAmount',
		name: 'shippingTaxAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'shippingTaxAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'miscAmount',
		name: 'miscAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'miscAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'miscTaxAmount',
		name: 'miscTaxAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'miscTaxAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'chargeAndAllowanceAmount',
		name: 'chargeAndAllowanceAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'chargeAndAllowanceAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'stockable',
		name: 'stockable',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'stockable',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'costable',
		name: 'costable',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'costable',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'taxable',
		name: 'taxable',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'taxable',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'taxableAmount',
		name: 'taxableAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'taxableAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'nonTaxableAmount',
		name: 'nonTaxableAmount',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'nonTaxableAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'isAp',
		name: 'isAp',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'isAp',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'warehouseCode',
		name: 'warehouseCode',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'warehouseCode',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updateDateUtc',
		name: 'updateDateUtc',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updateDateUtc',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'enterBy',
		name: 'enterBy',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'enterBy',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updateBy',
		name: 'updateBy',
		parentName: 'poItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updateBy',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
];
*/
//#endregion all grid columns for PoItems
// display columns in screen grid
const gridColumns: any[] = [
];

export const poItemsGrid = { 
	grid: {
        name: 'poItems',
	    idProperty: 'rid',
        // className: '',
        // bgColor: '',
        // color: '',
        // width: '100%',
        // minWidth: null,
        height: 500,
        // minHeight: 500,

        // hide: false,
        // systemHide?: false,
        // readOnly?: false,
        // reverseScreenReadOnly?: false,
        // disabled?: false,

        // enableEip: true,
        // enableSort: true,
        // enableSelect: true,
        // enableInsert: true,
        // enableDelete: true,
        // showRowNo: true,
        // enableRowNoButton: true,      // Add row no as button. { name: `btnRowNo_${gridName}`, moreData: { gridName, rid } }

        columns: gridColumns,
	},
	editer: {
	//#region grid editor for PoItems
	seq: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'seq',
		placeholder: 'seq',
		format: 'number',
		textStyle: {},
	},
	poItemType: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'poItemType',
		placeholder: 'poItemType',
		format: 'number',
		textStyle: {},
	},
	poItemStatus: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'poItemStatus',
		placeholder: 'poItemStatus',
		format: 'number',
		textStyle: {},
	},
	poDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'poItems',
		name: 'poDate',
		placeholder: 'poDate',
		format: 'date',
		textStyle: {},
	},
	poTime: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'poItems',
		name: 'poTime',
		placeholder: 'poTime',
		format: 'time',
		textStyle: {},
	},
	etaShipDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'poItems',
		name: 'etaShipDate',
		placeholder: 'etaShipDate',
		format: 'date',
		textStyle: {},
	},
	etaArrivalDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'poItems',
		name: 'etaArrivalDate',
		placeholder: 'etaArrivalDate',
		format: 'date',
		textStyle: {},
	},
	cancelDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'poItems',
		name: 'cancelDate',
		placeholder: 'cancelDate',
		format: 'date',
		textStyle: {},
	},
	sku: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'poItems',
		name: 'sku',
		placeholder: 'sku',
		maxLength: 100,
		textStyle: {},
	},
	description: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'poItems',
		name: 'description',
		placeholder: 'description',
		maxLength: 200,
		textStyle: {},
	},
	notes: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'poItems',
		name: 'notes',
		placeholder: 'notes',
		maxLength: 500,
		textStyle: {},
	},
	itemTotalAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'itemTotalAmount',
		placeholder: 'itemTotalAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	currency: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'poItems',
		name: 'currency',
		placeholder: 'currency',
		maxLength: 10,
		textStyle: {},
	},
	poQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'poQty',
		placeholder: 'poQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	receivedQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'receivedQty',
		placeholder: 'receivedQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	cancelledQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'cancelledQty',
		placeholder: 'cancelledQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	priceRule: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'poItems',
		name: 'priceRule',
		placeholder: 'priceRule',
		maxLength: 50,
		textStyle: {},
	},
	price: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'price',
		placeholder: 'price',
		format: 'price',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	extAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'extAmount',
		placeholder: 'extAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	taxRate: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'taxRate',
		placeholder: 'taxRate',
		format: 'taxRate',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	taxAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'taxAmount',
		placeholder: 'taxAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	discountPrice: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'discountPrice',
		placeholder: 'discountPrice',
		format: 'price',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	discountRate: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'discountRate',
		placeholder: 'discountRate',
		format: 'rate',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	discountAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'discountAmount',
		placeholder: 'discountAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	shippingAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'shippingAmount',
		placeholder: 'shippingAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	shippingTaxAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'shippingTaxAmount',
		placeholder: 'shippingTaxAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	miscAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'miscAmount',
		placeholder: 'miscAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	miscTaxAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'miscTaxAmount',
		placeholder: 'miscTaxAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	chargeAndAllowanceAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'chargeAndAllowanceAmount',
		placeholder: 'chargeAndAllowanceAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	stockable: {
		type: DbComponentEnums.inputTypeEnum.checkbox,
		parentName: 'poItems',
		name: 'stockable',
		placeholder: 'stockable',
		textStyle: {},
	},
	costable: {
		type: DbComponentEnums.inputTypeEnum.checkbox,
		parentName: 'poItems',
		name: 'costable',
		placeholder: 'costable',
		textStyle: {},
	},
	taxable: {
		type: DbComponentEnums.inputTypeEnum.checkbox,
		parentName: 'poItems',
		name: 'taxable',
		placeholder: 'taxable',
		textStyle: {},
	},
	taxableAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'taxableAmount',
		placeholder: 'taxableAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	nonTaxableAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'poItems',
		name: 'nonTaxableAmount',
		placeholder: 'nonTaxableAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	isAp: {
		type: DbComponentEnums.inputTypeEnum.checkbox,
		parentName: 'poItems',
		name: 'isAp',
		placeholder: 'isAp',
		textStyle: {},
	},
	warehouseCode: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'poItems',
		name: 'warehouseCode',
		placeholder: 'warehouseCode',
		maxLength: 50,
		textStyle: {},
	},
	updateDateUtc: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'poItems',
		name: 'updateDateUtc',
		placeholder: 'updateDateUtc',
		format: 'date',
		textStyle: {},
	},
	enterBy: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'poItems',
		name: 'enterBy',
		placeholder: 'enterBy',
		maxLength: 100,
		textStyle: {},
	},
	updateBy: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'poItems',
		name: 'updateBy',
		placeholder: 'updateBy',
		maxLength: 100,
		textStyle: {},
	},
	//#endregion grid editor for PoItems
	}
};



