import { ScreenType, ProcessMode } from '../../types/enums';
import { DbComponentEnums } from '../../types';
import { IconNames } from '../../components/icon';
import { btnSave, btnEdit, btnList, btnDelete } from '../default';
import * as util from '../../util';

import { poItemsGrid } from './poItems.grid';
export const purchaseOrderUi = { 
    page: {
        screenType: ScreenType.PROCESSING,
        screenid: 1001,
        processMode: ProcessMode.LIST,
        title: 'PurchaseOrder',
        subTitle: '',
        readonly: false,
    },
    header: {
        title: 'PurchaseOrder',
    },
    navbar: {},
    section: {},
    buttonGroup: {},
    buttons: {
        btnSave,
        btnEdit, 
        btnList, 
        btnDelete,
    },
	ui: {
		//#region UI control for PoHeader
		poNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeader',
			name: 'poNum',
			label: 'poNum',
			placeholder: 'poNum',
			maxLength: 50,
			textStyle: {},
		},
		poType: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'poType',
			label: 'poType',
			placeholder: 'poType',
			format: 'number',
			textStyle: {},
		},
		poStatus: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'poStatus',
			label: 'poStatus',
			placeholder: 'poStatus',
			format: 'number',
			textStyle: {},
		},
		poDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'poHeader',
			name: 'poDate',
			label: 'poDate',
			placeholder: 'poDate',
			format: 'date',
			textStyle: {},
		},
		poTime: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeader',
			name: 'poTime',
			label: 'poTime',
			placeholder: 'poTime',
			format: 'time',
			textStyle: {},
		},
		etaShipDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'poHeader',
			name: 'etaShipDate',
			label: 'etaShipDate',
			placeholder: 'etaShipDate',
			format: 'date',
			textStyle: {},
		},
		etaArrivalDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'poHeader',
			name: 'etaArrivalDate',
			label: 'etaArrivalDate',
			placeholder: 'etaArrivalDate',
			format: 'date',
			textStyle: {},
		},
		cancelDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'poHeader',
			name: 'cancelDate',
			label: 'cancelDate',
			placeholder: 'cancelDate',
			format: 'date',
			textStyle: {},
		},
		vendorNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeader',
			name: 'vendorNum',
			label: 'vendorNum',
			placeholder: 'vendorNum',
			maxLength: 50,
			textStyle: {},
		},
		vendorName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeader',
			name: 'vendorName',
			label: 'vendorName',
			placeholder: 'vendorName',
			maxLength: 100,
			textStyle: {},
		},
		currency: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeader',
			name: 'currency',
			label: 'currency',
			placeholder: 'currency',
			maxLength: 10,
			textStyle: {},
		},
		subTotalAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'subTotalAmount',
			label: 'subTotalAmount',
			placeholder: 'subTotalAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		totalAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'totalAmount',
			label: 'totalAmount',
			placeholder: 'totalAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		taxRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'taxRate',
			label: 'taxRate',
			placeholder: 'taxRate',
			format: 'taxRate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		taxAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'taxAmount',
			label: 'taxAmount',
			placeholder: 'taxAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		taxableAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'taxableAmount',
			label: 'taxableAmount',
			placeholder: 'taxableAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		nonTaxableAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'nonTaxableAmount',
			label: 'nonTaxableAmount',
			placeholder: 'nonTaxableAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		discountRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'discountRate',
			label: 'discountRate',
			placeholder: 'discountRate',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		discountAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'discountAmount',
			label: 'discountAmount',
			placeholder: 'discountAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		shippingAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'shippingAmount',
			label: 'shippingAmount',
			placeholder: 'shippingAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		shippingTaxAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'shippingTaxAmount',
			label: 'shippingTaxAmount',
			placeholder: 'shippingTaxAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		miscAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'miscAmount',
			label: 'miscAmount',
			placeholder: 'miscAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		miscTaxAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'miscTaxAmount',
			label: 'miscTaxAmount',
			placeholder: 'miscTaxAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		chargeAndAllowanceAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeader',
			name: 'chargeAndAllowanceAmount',
			label: 'chargeAndAllowanceAmount',
			placeholder: 'chargeAndAllowanceAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		poSourceCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeader',
			name: 'poSourceCode',
			label: 'poSourceCode',
			placeholder: 'poSourceCode',
			maxLength: 100,
			textStyle: {},
		},
		updateDateUtc: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'poHeader',
			name: 'updateDateUtc',
			label: 'updateDateUtc',
			placeholder: 'updateDateUtc',
			format: 'date',
			textStyle: {},
		},
		enterBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeader',
			name: 'enterBy',
			label: 'enterBy',
			placeholder: 'enterBy',
			maxLength: 100,
			textStyle: {},
		},
		updateBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeader',
			name: 'updateBy',
			label: 'updateBy',
			placeholder: 'updateBy',
			maxLength: 100,
			textStyle: {},
		},
		//#endregion UI control for PoHeader



		//#region UI control for PoHeaderInfo
		centralFulfillmentNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeaderInfo',
			name: 'centralFulfillmentNum',
			label: 'centralFulfillmentNum',
			placeholder: 'centralFulfillmentNum',
			format: 'number',
			textStyle: {},
		},
		shippingCarrier: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shippingCarrier',
			label: 'shippingCarrier',
			placeholder: 'shippingCarrier',
			maxLength: 50,
			textStyle: {},
		},
		shippingClass: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shippingClass',
			label: 'shippingClass',
			placeholder: 'shippingClass',
			maxLength: 50,
			textStyle: {},
		},
		centralOrderNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'poHeaderInfo',
			name: 'centralOrderNum',
			label: 'centralOrderNum',
			placeholder: 'centralOrderNum',
			format: 'number',
			textStyle: {},
		},
		channelOrderID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'channelOrderID',
			label: 'channelOrderID',
			placeholder: 'channelOrderID',
			maxLength: 130,
			textStyle: {},
		},
		secondaryChannelOrderID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'secondaryChannelOrderID',
			label: 'secondaryChannelOrderID',
			placeholder: 'secondaryChannelOrderID',
			maxLength: 200,
			textStyle: {},
		},
		shippingAccount: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shippingAccount',
			label: 'shippingAccount',
			placeholder: 'shippingAccount',
			maxLength: 100,
			textStyle: {},
		},
		refNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'refNum',
			label: 'refNum',
			placeholder: 'refNum',
			maxLength: 100,
			textStyle: {},
		},
		customerPoNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'customerPoNum',
			label: 'customerPoNum',
			placeholder: 'customerPoNum',
			maxLength: 100,
			textStyle: {},
		},
		endBuyerUserID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'endBuyerUserID',
			label: 'endBuyerUserID',
			placeholder: 'endBuyerUserID',
			maxLength: 255,
			textStyle: {},
		},
		endBuyerName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'endBuyerName',
			label: 'endBuyerName',
			placeholder: 'endBuyerName',
			maxLength: 255,
			textStyle: {},
		},
		endBuyerEmail: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'endBuyerEmail',
			label: 'endBuyerEmail',
			placeholder: 'endBuyerEmail',
			maxLength: 255,
			textStyle: {},
		},
		shipToName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToName',
			label: 'shipToName',
			placeholder: 'shipToName',
			maxLength: 100,
			textStyle: {},
		},
		shipToCompany: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToCompany',
			label: 'shipToCompany',
			placeholder: 'shipToCompany',
			maxLength: 100,
			textStyle: {},
		},
		shipToAttention: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToAttention',
			label: 'shipToAttention',
			placeholder: 'shipToAttention',
			maxLength: 100,
			textStyle: {},
		},
		shipToAddressLine1: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToAddressLine1',
			label: 'shipToAddressLine1',
			placeholder: 'shipToAddressLine1',
			maxLength: 200,
			textStyle: {},
		},
		shipToAddressLine2: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToAddressLine2',
			label: 'shipToAddressLine2',
			placeholder: 'shipToAddressLine2',
			maxLength: 200,
			textStyle: {},
		},
		shipToCity: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToCity',
			label: 'shipToCity',
			placeholder: 'shipToCity',
			maxLength: 100,
			textStyle: {},
		},
		shipToState: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToState',
			label: 'shipToState',
			placeholder: 'shipToState',
			maxLength: 50,
			textStyle: {},
		},
		shipToStateFullName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToStateFullName',
			label: 'shipToStateFullName',
			placeholder: 'shipToStateFullName',
			maxLength: 100,
			textStyle: {},
		},
		shipToPostalCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToPostalCode',
			label: 'shipToPostalCode',
			placeholder: 'shipToPostalCode',
			maxLength: 50,
			textStyle: {},
		},
		shipToPostalCodeExt: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToPostalCodeExt',
			label: 'shipToPostalCodeExt',
			placeholder: 'shipToPostalCodeExt',
			maxLength: 50,
			textStyle: {},
		},
		shipToCounty: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToCounty',
			label: 'shipToCounty',
			placeholder: 'shipToCounty',
			maxLength: 100,
			textStyle: {},
		},
		shipToCountry: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToCountry',
			label: 'shipToCountry',
			placeholder: 'shipToCountry',
			maxLength: 100,
			textStyle: {},
		},
		shipToEmail: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToEmail',
			label: 'shipToEmail',
			placeholder: 'shipToEmail',
			maxLength: 100,
			textStyle: {},
		},
		shipToDaytimePhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToDaytimePhone',
			label: 'shipToDaytimePhone',
			placeholder: 'shipToDaytimePhone',
			maxLength: 50,
			textStyle: {},
		},
		shipToNightPhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'shipToNightPhone',
			label: 'shipToNightPhone',
			placeholder: 'shipToNightPhone',
			maxLength: 50,
			textStyle: {},
		},
		billToName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToName',
			label: 'billToName',
			placeholder: 'billToName',
			maxLength: 100,
			textStyle: {},
		},
		billToCompany: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToCompany',
			label: 'billToCompany',
			placeholder: 'billToCompany',
			maxLength: 100,
			textStyle: {},
		},
		billToAttention: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToAttention',
			label: 'billToAttention',
			placeholder: 'billToAttention',
			maxLength: 100,
			textStyle: {},
		},
		billToAddressLine1: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToAddressLine1',
			label: 'billToAddressLine1',
			placeholder: 'billToAddressLine1',
			maxLength: 200,
			textStyle: {},
		},
		billToAddressLine2: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToAddressLine2',
			label: 'billToAddressLine2',
			placeholder: 'billToAddressLine2',
			maxLength: 200,
			textStyle: {},
		},
		billToCity: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToCity',
			label: 'billToCity',
			placeholder: 'billToCity',
			maxLength: 100,
			textStyle: {},
		},
		billToState: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToState',
			label: 'billToState',
			placeholder: 'billToState',
			maxLength: 50,
			textStyle: {},
		},
		billToStateFullName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToStateFullName',
			label: 'billToStateFullName',
			placeholder: 'billToStateFullName',
			maxLength: 100,
			textStyle: {},
		},
		billToPostalCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToPostalCode',
			label: 'billToPostalCode',
			placeholder: 'billToPostalCode',
			maxLength: 50,
			textStyle: {},
		},
		billToPostalCodeExt: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToPostalCodeExt',
			label: 'billToPostalCodeExt',
			placeholder: 'billToPostalCodeExt',
			maxLength: 50,
			textStyle: {},
		},
		billToCounty: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToCounty',
			label: 'billToCounty',
			placeholder: 'billToCounty',
			maxLength: 50,
			textStyle: {},
		},
		billToCountry: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToCountry',
			label: 'billToCountry',
			placeholder: 'billToCountry',
			maxLength: 100,
			textStyle: {},
		},
		billToEmail: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToEmail',
			label: 'billToEmail',
			placeholder: 'billToEmail',
			maxLength: 100,
			textStyle: {},
		},
		billToDaytimePhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToDaytimePhone',
			label: 'billToDaytimePhone',
			placeholder: 'billToDaytimePhone',
			maxLength: 50,
			textStyle: {},
		},
		billToNightPhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'poHeaderInfo',
			name: 'billToNightPhone',
			label: 'billToNightPhone',
			placeholder: 'billToNightPhone',
			maxLength: 50,
			textStyle: {},
		},
		//#endregion UI control for PoHeaderInfo



		//#region UI control for PoHeaderAttributes
		//#endregion UI control for PoHeaderAttributes



	},

    grid: {
		poItems: poItemsGrid,
    },
    modal: {},
    menu: {},
};

