import { DbComponentEnums } from '../../types';
import { IconNames } from '../../components/icon';
import * as util from '../../util';

//#region all grid columns for InvoiceReturnItems
/** copy column's define object to gridColumns will display column in screen.
const allColumns = [
	{
		id: 'rid',
		name: 'rid',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.hiden,
		defaultFlex: 1,
		systemHide: true,
	},
	{
		id: 'rno',
		name: 'rno',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.rowNo,
		header: '#',
		align: DbComponentEnums.alignEnum.center,
		defaultFlex: 1,
		textStyle: {},
		sortable: false,
		hide: true,
	},
	{
		id: 'seq',
		name: 'seq',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'seq',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'returnItemType',
		name: 'returnItemType',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'returnItemType',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'returnItemStatus',
		name: 'returnItemStatus',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'returnItemStatus',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'number',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'returnDate',
		name: 'returnDate',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'returnDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'returnTime',
		name: 'returnTime',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'returnTime',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		format: 'time',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'receiveDate',
		name: 'receiveDate',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'receiveDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'stockDate',
		name: 'stockDate',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'stockDate',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'sku',
		name: 'sku',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'sku',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'invoiceWarehouseCode',
		name: 'invoiceWarehouseCode',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'invoiceWarehouseCode',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'warehouseCode',
		name: 'warehouseCode',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'warehouseCode',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'lotNum',
		name: 'lotNum',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'lotNum',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'reason',
		name: 'reason',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'reason',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'description',
		name: 'description',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'description',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'notes',
		name: 'notes',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'notes',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'currency',
		name: 'currency',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'currency',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'uom',
		name: 'uom',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'uom',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packType',
		name: 'packType',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packType',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'packQty',
		name: 'packQty',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'packQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'returnPack',
		name: 'returnPack',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'returnPack',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'receivePack',
		name: 'receivePack',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'receivePack',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'stockPack',
		name: 'stockPack',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'stockPack',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'nonStockPack',
		name: 'nonStockPack',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'nonStockPack',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'decimalNumber',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'returnQty',
		name: 'returnQty',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'returnQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'receiveQty',
		name: 'receiveQty',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'receiveQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'stockQty',
		name: 'stockQty',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'stockQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'nonStockQty',
		name: 'nonStockQty',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'nonStockQty',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'qty',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'putBackWarehouseCode',
		name: 'putBackWarehouseCode',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'putBackWarehouseCode',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'damageWarehouseCode',
		name: 'damageWarehouseCode',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'damageWarehouseCode',
		defaultFlex: 2,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'invoiceDiscountPrice',
		name: 'invoiceDiscountPrice',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'invoiceDiscountPrice',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'price',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'invoiceDiscountAmount',
		name: 'invoiceDiscountAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'invoiceDiscountAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'returnDiscountAmount',
		name: 'returnDiscountAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'returnDiscountAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'price',
		name: 'price',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'price',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'price',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'extAmount',
		name: 'extAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'extAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'taxableAmount',
		name: 'taxableAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'taxableAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'nonTaxableAmount',
		name: 'nonTaxableAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'nonTaxableAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'taxRate',
		name: 'taxRate',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'taxRate',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'taxRate',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'taxAmount',
		name: 'taxAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'taxAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'shippingAmount',
		name: 'shippingAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'shippingAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'shippingTaxAmount',
		name: 'shippingTaxAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'shippingTaxAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'miscAmount',
		name: 'miscAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'miscAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'miscTaxAmount',
		name: 'miscTaxAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'miscTaxAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'chargeAndAllowanceAmount',
		name: 'chargeAndAllowanceAmount',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'chargeAndAllowanceAmount',
		align: DbComponentEnums.alignEnum.right,
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.number,
		format: 'amount',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'stockable',
		name: 'stockable',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'stockable',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'isAr',
		name: 'isAr',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'isAr',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'taxable',
		name: 'taxable',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'taxable',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updateDateUtc',
		name: 'updateDateUtc',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updateDateUtc',
		defaultFlex: 1,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.date,
		format: 'date',
		enableEdit: false,
		hide: true,
	},
	{
		id: 'enterBy',
		name: 'enterBy',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'enterBy',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
	{
		id: 'updateBy',
		name: 'updateBy',
		parentName: 'invoiceReturnItems',
		columnType: DbComponentEnums.gridColumnTypeEnum.text,
		header: 'updateBy',
		defaultFlex: 4,
		textStyle: {},
		sortable: true,
		sortType: DbComponentEnums.gridSortEnum.string,
		enableEdit: false,
		hide: true,
	},
];
*/
//#endregion all grid columns for InvoiceReturnItems
// display columns in screen grid
const gridColumns: any[] = [
];

export const invoiceReturnItemsGrid = { 
	grid: {
        name: 'invoiceReturnItems',
	    idProperty: 'rid',
        // className: '',
        // bgColor: '',
        // color: '',
        // width: '100%',
        // minWidth: null,
        height: 500,
        // minHeight: 500,

        // hide: false,
        // systemHide?: false,
        // readOnly?: false,
        // reverseScreenReadOnly?: false,
        // disabled?: false,

        // enableEip: true,
        // enableSort: true,
        // enableSelect: true,
        // enableInsert: true,
        // enableDelete: true,
        // showRowNo: true,
        // enableRowNoButton: true,      // Add row no as button. { name: `btnRowNo_${gridName}`, moreData: { gridName, rid } }

        columns: gridColumns,
	},
	editer: {
	//#region grid editor for InvoiceReturnItems
	seq: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'seq',
		placeholder: 'seq',
		format: 'number',
		textStyle: {},
	},
	returnItemType: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'returnItemType',
		placeholder: 'returnItemType',
		format: 'number',
		textStyle: {},
	},
	returnItemStatus: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'returnItemStatus',
		placeholder: 'returnItemStatus',
		format: 'number',
		textStyle: {},
	},
	returnDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'invoiceReturnItems',
		name: 'returnDate',
		placeholder: 'returnDate',
		format: 'date',
		textStyle: {},
	},
	returnTime: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'returnTime',
		placeholder: 'returnTime',
		format: 'time',
		textStyle: {},
	},
	receiveDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'invoiceReturnItems',
		name: 'receiveDate',
		placeholder: 'receiveDate',
		format: 'date',
		textStyle: {},
	},
	stockDate: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'invoiceReturnItems',
		name: 'stockDate',
		placeholder: 'stockDate',
		format: 'date',
		textStyle: {},
	},
	sku: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'sku',
		placeholder: 'sku',
		maxLength: 100,
		textStyle: {},
	},
	invoiceWarehouseCode: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'invoiceWarehouseCode',
		placeholder: 'invoiceWarehouseCode',
		maxLength: 50,
		textStyle: {},
	},
	warehouseCode: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'warehouseCode',
		placeholder: 'warehouseCode',
		maxLength: 50,
		textStyle: {},
	},
	lotNum: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'lotNum',
		placeholder: 'lotNum',
		maxLength: 100,
		textStyle: {},
	},
	reason: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'reason',
		placeholder: 'reason',
		maxLength: 200,
		textStyle: {},
	},
	description: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'description',
		placeholder: 'description',
		maxLength: 200,
		textStyle: {},
	},
	notes: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'notes',
		placeholder: 'notes',
		maxLength: 500,
		textStyle: {},
	},
	currency: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'currency',
		placeholder: 'currency',
		maxLength: 10,
		textStyle: {},
	},
	uom: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'uom',
		placeholder: 'uom',
		maxLength: 50,
		textStyle: {},
	},
	packType: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'packType',
		placeholder: 'packType',
		maxLength: 50,
		textStyle: {},
	},
	packQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'packQty',
		placeholder: 'packQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	returnPack: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'returnPack',
		placeholder: 'returnPack',
		format: 'decimalNumber',
		textStyle: {},
	},
	receivePack: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'receivePack',
		placeholder: 'receivePack',
		format: 'decimalNumber',
		textStyle: {},
	},
	stockPack: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'stockPack',
		placeholder: 'stockPack',
		format: 'decimalNumber',
		textStyle: {},
	},
	nonStockPack: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'nonStockPack',
		placeholder: 'nonStockPack',
		format: 'decimalNumber',
		textStyle: {},
	},
	returnQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'returnQty',
		placeholder: 'returnQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	receiveQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'receiveQty',
		placeholder: 'receiveQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	stockQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'stockQty',
		placeholder: 'stockQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	nonStockQty: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'nonStockQty',
		placeholder: 'nonStockQty',
		format: 'qty',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	putBackWarehouseCode: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'putBackWarehouseCode',
		placeholder: 'putBackWarehouseCode',
		maxLength: 50,
		textStyle: {},
	},
	damageWarehouseCode: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'damageWarehouseCode',
		placeholder: 'damageWarehouseCode',
		maxLength: 50,
		textStyle: {},
	},
	invoiceDiscountPrice: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'invoiceDiscountPrice',
		placeholder: 'invoiceDiscountPrice',
		format: 'price',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	invoiceDiscountAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'invoiceDiscountAmount',
		placeholder: 'invoiceDiscountAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	returnDiscountAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'returnDiscountAmount',
		placeholder: 'returnDiscountAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	price: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'price',
		placeholder: 'price',
		format: 'price',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	extAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'extAmount',
		placeholder: 'extAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	taxableAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'taxableAmount',
		placeholder: 'taxableAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	nonTaxableAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'nonTaxableAmount',
		placeholder: 'nonTaxableAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	taxRate: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'taxRate',
		placeholder: 'taxRate',
		format: 'taxRate',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	taxAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'taxAmount',
		placeholder: 'taxAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	shippingAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'shippingAmount',
		placeholder: 'shippingAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	shippingTaxAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'shippingTaxAmount',
		placeholder: 'shippingTaxAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	miscAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'miscAmount',
		placeholder: 'miscAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	miscTaxAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'miscTaxAmount',
		placeholder: 'miscTaxAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	chargeAndAllowanceAmount: {
		type: DbComponentEnums.inputTypeEnum.number,
		parentName: 'invoiceReturnItems',
		name: 'chargeAndAllowanceAmount',
		placeholder: 'chargeAndAllowanceAmount',
		format: 'amount',
		align: DbComponentEnums.alignEnum.right,
		textStyle: {},
	},
	stockable: {
		type: DbComponentEnums.inputTypeEnum.checkbox,
		parentName: 'invoiceReturnItems',
		name: 'stockable',
		placeholder: 'stockable',
		textStyle: {},
	},
	isAr: {
		type: DbComponentEnums.inputTypeEnum.checkbox,
		parentName: 'invoiceReturnItems',
		name: 'isAr',
		placeholder: 'isAr',
		textStyle: {},
	},
	taxable: {
		type: DbComponentEnums.inputTypeEnum.checkbox,
		parentName: 'invoiceReturnItems',
		name: 'taxable',
		placeholder: 'taxable',
		textStyle: {},
	},
	updateDateUtc: {
		type: DbComponentEnums.inputTypeEnum.date,
		parentName: 'invoiceReturnItems',
		name: 'updateDateUtc',
		placeholder: 'updateDateUtc',
		format: 'date',
		textStyle: {},
	},
	enterBy: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'enterBy',
		placeholder: 'enterBy',
		maxLength: 100,
		textStyle: {},
	},
	updateBy: {
		type: DbComponentEnums.inputTypeEnum.input,
		parentName: 'invoiceReturnItems',
		name: 'updateBy',
		placeholder: 'updateBy',
		maxLength: 100,
		textStyle: {},
	},
	//#endregion grid editor for InvoiceReturnItems
	}
};



