import { ScreenType, ProcessMode } from '../../types/enums';
import { DbComponentEnums } from '../../types';
import { IconNames } from '../../components/icon';
import { btnSave, btnEdit, btnList, btnDelete } from '../default';
import * as util from '../../util';

import { invoiceReturnItemsGrid } from './invoiceReturnItems.grid';
export const invoiceTransactionUi = { 
    page: {
        screenType: ScreenType.PROCESSING,
        screenid: 1001,
        processMode: ProcessMode.LIST,
        title: 'InvoiceTransaction',
        subTitle: '',
        readonly: false,
    },
    header: {
        title: 'InvoiceTransaction',
    },
    navbar: {},
    section: {},
    buttonGroup: {},
    buttons: {
        btnSave,
        btnEdit, 
        btnList, 
        btnDelete,
    },
	ui: {
		//#region UI control for InvoiceTransaction
		transNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'transNum',
			label: 'transNum',
			placeholder: 'transNum',
			format: 'number',
			textStyle: {},
		},
		invoiceNumber: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'invoiceNumber',
			label: 'invoiceNumber',
			placeholder: 'invoiceNumber',
			maxLength: 50,
			textStyle: {},
		},
		transType: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'transType',
			label: 'transType',
			placeholder: 'transType',
			format: 'number',
			textStyle: {},
		},
		transStatus: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'transStatus',
			label: 'transStatus',
			placeholder: 'transStatus',
			format: 'number',
			textStyle: {},
		},
		transDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'invoiceTransaction',
			name: 'transDate',
			label: 'transDate',
			placeholder: 'transDate',
			format: 'date',
			textStyle: {},
		},
		transTime: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'transTime',
			label: 'transTime',
			placeholder: 'transTime',
			format: 'time',
			textStyle: {},
		},
		description: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'description',
			label: 'description',
			placeholder: 'description',
			maxLength: 100,
			textStyle: {},
		},
		notes: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'notes',
			label: 'notes',
			placeholder: 'notes',
			maxLength: 500,
			textStyle: {},
		},
		paidBy: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'paidBy',
			label: 'paidBy',
			placeholder: 'paidBy',
			format: 'number',
			textStyle: {},
		},
		bankAccountCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'bankAccountCode',
			label: 'bankAccountCode',
			placeholder: 'bankAccountCode',
			maxLength: 50,
			textStyle: {},
		},
		checkNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'checkNum',
			label: 'checkNum',
			placeholder: 'checkNum',
			maxLength: 100,
			textStyle: {},
		},
		authCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'authCode',
			label: 'authCode',
			placeholder: 'authCode',
			maxLength: 100,
			textStyle: {},
		},
		currency: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'currency',
			label: 'currency',
			placeholder: 'currency',
			maxLength: 10,
			textStyle: {},
		},
		exchangeRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'exchangeRate',
			label: 'exchangeRate',
			placeholder: 'exchangeRate',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		subTotalAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'subTotalAmount',
			label: 'subTotalAmount',
			placeholder: 'subTotalAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		salesAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'salesAmount',
			label: 'salesAmount',
			placeholder: 'salesAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		totalAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'totalAmount',
			label: 'totalAmount',
			placeholder: 'totalAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		taxableAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'taxableAmount',
			label: 'taxableAmount',
			placeholder: 'taxableAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		nonTaxableAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'nonTaxableAmount',
			label: 'nonTaxableAmount',
			placeholder: 'nonTaxableAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		taxRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'taxRate',
			label: 'taxRate',
			placeholder: 'taxRate',
			format: 'taxRate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		taxAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'taxAmount',
			label: 'taxAmount',
			placeholder: 'taxAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		discountRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'discountRate',
			label: 'discountRate',
			placeholder: 'discountRate',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		discountAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'discountAmount',
			label: 'discountAmount',
			placeholder: 'discountAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		shippingAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'shippingAmount',
			label: 'shippingAmount',
			placeholder: 'shippingAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		shippingTaxAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'shippingTaxAmount',
			label: 'shippingTaxAmount',
			placeholder: 'shippingTaxAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		miscAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'miscAmount',
			label: 'miscAmount',
			placeholder: 'miscAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		miscTaxAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'miscTaxAmount',
			label: 'miscTaxAmount',
			placeholder: 'miscTaxAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		chargeAndAllowanceAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'chargeAndAllowanceAmount',
			label: 'chargeAndAllowanceAmount',
			placeholder: 'chargeAndAllowanceAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		creditAccount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'creditAccount',
			label: 'creditAccount',
			placeholder: 'creditAccount',
			format: 'number',
			textStyle: {},
		},
		debitAccount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'invoiceTransaction',
			name: 'debitAccount',
			label: 'debitAccount',
			placeholder: 'debitAccount',
			format: 'number',
			textStyle: {},
		},
		transSourceCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'transSourceCode',
			label: 'transSourceCode',
			placeholder: 'transSourceCode',
			maxLength: 100,
			textStyle: {},
		},
		updateDateUtc: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'invoiceTransaction',
			name: 'updateDateUtc',
			label: 'updateDateUtc',
			placeholder: 'updateDateUtc',
			format: 'date',
			textStyle: {},
		},
		enterBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'enterBy',
			label: 'enterBy',
			placeholder: 'enterBy',
			maxLength: 100,
			textStyle: {},
		},
		updateBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'invoiceTransaction',
			name: 'updateBy',
			label: 'updateBy',
			placeholder: 'updateBy',
			maxLength: 100,
			textStyle: {},
		},
		//#endregion UI control for InvoiceTransaction



	},

    grid: {
		invoiceReturnItems: invoiceReturnItemsGrid,
    },
    modal: {},
    menu: {},
};

