import { ScreenType, ProcessMode } from '../../types/enums';
import { DbComponentEnums, Enums } from '../../types';
import { IconNames } from '../../components/icon';
import { btnSave, btnEdit, btnList, btnDelete } from '../default';
import * as util from '../../util';

import { salesOrderItemsGrid } from './salesOrderItems.grid';
export const salesOrderUi = { 
    page: {
        screenType: ScreenType.PROCESSING,
        screenid: 1001,
        processMode: ProcessMode.LIST,
        processModeList: [Enums.ProcessMode.LIST],
        title: 'SalesOrder',
        subTitle: '',
        readonly: false,
    },
    header: {
        title: 'SalesOrder',
    },
    navbar: {},
    section: {},
    buttonGroup: {},
    buttons: {
        btnSave,
        btnEdit, 
        btnList, 
        btnDelete,
    },
	ui: {
		//#region UI control for SalesOrderHeader
		orderNumber: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'orderNumber',
			label: 'orderNumber',
			placeholder: 'orderNumber',
			maxLength: 50,
			textStyle: {},
		},
		orderType: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'orderType',
			label: 'orderType',
			placeholder: 'orderType',
			format: 'number',
			textStyle: {},
		},
		orderStatus: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'orderStatus',
			label: 'orderStatus',
			placeholder: 'orderStatus',
			format: 'number',
			textStyle: {},
		},
		orderDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'salesOrderHeader',
			name: 'orderDate',
			label: 'orderDate',
			placeholder: 'orderDate',
			format: 'date',
			textStyle: {},
		},
		orderTime: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'orderTime',
			label: 'orderTime',
			placeholder: 'orderTime',
			format: 'time',
			textStyle: {},
		},
		shipDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'salesOrderHeader',
			name: 'shipDate',
			label: 'shipDate',
			placeholder: 'shipDate',
			format: 'date',
			textStyle: {},
		},
		dueDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'salesOrderHeader',
			name: 'dueDate',
			label: 'dueDate',
			placeholder: 'dueDate',
			format: 'date',
			textStyle: {},
		},
		billDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'salesOrderHeader',
			name: 'billDate',
			label: 'billDate',
			placeholder: 'billDate',
			format: 'date',
			textStyle: {},
		},
		etaArrivalDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'salesOrderHeader',
			name: 'etaArrivalDate',
			label: 'etaArrivalDate',
			placeholder: 'etaArrivalDate',
			format: 'date',
			textStyle: {},
		},
		earliestShipDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'salesOrderHeader',
			name: 'earliestShipDate',
			label: 'earliestShipDate',
			placeholder: 'earliestShipDate',
			format: 'date',
			textStyle: {},
		},
		latestShipDate: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'salesOrderHeader',
			name: 'latestShipDate',
			label: 'latestShipDate',
			placeholder: 'latestShipDate',
			format: 'date',
			textStyle: {},
		},
		signatureFlag: {
			type: DbComponentEnums.inputTypeEnum.checkbox,
			parentName: 'salesOrderHeader',
			name: 'signatureFlag',
			label: 'signatureFlag',
			placeholder: 'signatureFlag',
			textStyle: {},
		},
		customerCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'customerCode',
			label: 'customerCode',
			placeholder: 'customerCode',
			maxLength: 50,
			textStyle: {},
		},
		customerName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'customerName',
			label: 'customerName',
			placeholder: 'customerName',
			maxLength: 200,
			textStyle: {},
		},
		terms: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'terms',
			label: 'terms',
			placeholder: 'terms',
			maxLength: 50,
			textStyle: {},
		},
		termsDays: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'termsDays',
			label: 'termsDays',
			placeholder: 'termsDays',
			format: 'number',
			textStyle: {},
		},
		currency: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'currency',
			label: 'currency',
			placeholder: 'currency',
			maxLength: 10,
			textStyle: {},
		},
		subTotalAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'subTotalAmount',
			label: 'subTotalAmount',
			placeholder: 'subTotalAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		salesAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'salesAmount',
			label: 'salesAmount',
			placeholder: 'salesAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		totalAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'totalAmount',
			label: 'totalAmount',
			placeholder: 'totalAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		taxableAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'taxableAmount',
			label: 'taxableAmount',
			placeholder: 'taxableAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		nonTaxableAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'nonTaxableAmount',
			label: 'nonTaxableAmount',
			placeholder: 'nonTaxableAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		taxRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'taxRate',
			label: 'taxRate',
			placeholder: 'taxRate',
			format: 'taxRate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		taxAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'taxAmount',
			label: 'taxAmount',
			placeholder: 'taxAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		discountRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'discountRate',
			label: 'discountRate',
			placeholder: 'discountRate',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		discountAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'discountAmount',
			label: 'discountAmount',
			placeholder: 'discountAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		shippingAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'shippingAmount',
			label: 'shippingAmount',
			placeholder: 'shippingAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		shippingTaxAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'shippingTaxAmount',
			label: 'shippingTaxAmount',
			placeholder: 'shippingTaxAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		miscAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'miscAmount',
			label: 'miscAmount',
			placeholder: 'miscAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		miscTaxAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'miscTaxAmount',
			label: 'miscTaxAmount',
			placeholder: 'miscTaxAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		chargeAndAllowanceAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'chargeAndAllowanceAmount',
			label: 'chargeAndAllowanceAmount',
			placeholder: 'chargeAndAllowanceAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		channelAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'channelAmount',
			label: 'channelAmount',
			placeholder: 'channelAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		paidAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'paidAmount',
			label: 'paidAmount',
			placeholder: 'paidAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		creditAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'creditAmount',
			label: 'creditAmount',
			placeholder: 'creditAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		balance: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'balance',
			label: 'balance',
			placeholder: 'balance',
			format: 'decimalNumber',
			textStyle: {},
		},
		unitCost: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'unitCost',
			label: 'unitCost',
			placeholder: 'unitCost',
			format: 'cost',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		avgCost: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'avgCost',
			label: 'avgCost',
			placeholder: 'avgCost',
			format: 'cost',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		lotCost: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'lotCost',
			label: 'lotCost',
			placeholder: 'lotCost',
			format: 'cost',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		orderSourceCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'orderSourceCode',
			label: 'orderSourceCode',
			placeholder: 'orderSourceCode',
			maxLength: 100,
			textStyle: {},
		},
		depositAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'depositAmount',
			label: 'depositAmount',
			placeholder: 'depositAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		salesRep: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'salesRep',
			label: 'salesRep',
			placeholder: 'salesRep',
			maxLength: 100,
			textStyle: {},
		},
		salesRep2: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'salesRep2',
			label: 'salesRep2',
			placeholder: 'salesRep2',
			maxLength: 100,
			textStyle: {},
		},
		salesRep3: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'salesRep3',
			label: 'salesRep3',
			placeholder: 'salesRep3',
			maxLength: 100,
			textStyle: {},
		},
		salesRep4: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'salesRep4',
			label: 'salesRep4',
			placeholder: 'salesRep4',
			maxLength: 100,
			textStyle: {},
		},
		commissionRate: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'commissionRate',
			label: 'commissionRate',
			placeholder: 'commissionRate',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionRate2: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'commissionRate2',
			label: 'commissionRate2',
			placeholder: 'commissionRate2',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionRate3: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'commissionRate3',
			label: 'commissionRate3',
			placeholder: 'commissionRate3',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionRate4: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'commissionRate4',
			label: 'commissionRate4',
			placeholder: 'commissionRate4',
			format: 'rate',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionAmount: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'commissionAmount',
			label: 'commissionAmount',
			placeholder: 'commissionAmount',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionAmount2: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'commissionAmount2',
			label: 'commissionAmount2',
			placeholder: 'commissionAmount2',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionAmount3: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'commissionAmount3',
			label: 'commissionAmount3',
			placeholder: 'commissionAmount3',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		commissionAmount4: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeader',
			name: 'commissionAmount4',
			label: 'commissionAmount4',
			placeholder: 'commissionAmount4',
			format: 'amount',
			align: DbComponentEnums.alignEnum.right,
			textStyle: {},
		},
		updateDateUtc: {
			type: DbComponentEnums.inputTypeEnum.date,
			parentName: 'salesOrderHeader',
			name: 'updateDateUtc',
			label: 'updateDateUtc',
			placeholder: 'updateDateUtc',
			format: 'date',
			textStyle: {},
		},
		enterBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'enterBy',
			label: 'enterBy',
			placeholder: 'enterBy',
			maxLength: 100,
			textStyle: {},
		},
		updateBy: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeader',
			name: 'updateBy',
			label: 'updateBy',
			placeholder: 'updateBy',
			maxLength: 100,
			textStyle: {},
		},
		//#endregion UI control for SalesOrderHeader



		//#region UI control for SalesOrderHeaderInfo
		centralFulfillmentNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeaderInfo',
			name: 'centralFulfillmentNum',
			label: 'centralFulfillmentNum',
			placeholder: 'centralFulfillmentNum',
			format: 'number',
			textStyle: {},
		},
		shippingCarrier: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shippingCarrier',
			label: 'shippingCarrier',
			placeholder: 'shippingCarrier',
			maxLength: 50,
			textStyle: {},
		},
		shippingClass: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shippingClass',
			label: 'shippingClass',
			placeholder: 'shippingClass',
			maxLength: 50,
			textStyle: {},
		},
		centralOrderNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeaderInfo',
			name: 'centralOrderNum',
			label: 'centralOrderNum',
			placeholder: 'centralOrderNum',
			format: 'number',
			textStyle: {},
		},
		channelOrderID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'channelOrderID',
			label: 'channelOrderID',
			placeholder: 'channelOrderID',
			maxLength: 130,
			textStyle: {},
		},
		secondaryChannelOrderID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'secondaryChannelOrderID',
			label: 'secondaryChannelOrderID',
			placeholder: 'secondaryChannelOrderID',
			maxLength: 200,
			textStyle: {},
		},
		shippingAccount: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shippingAccount',
			label: 'shippingAccount',
			placeholder: 'shippingAccount',
			maxLength: 100,
			textStyle: {},
		},
		warehouseCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'warehouseCode',
			label: 'warehouseCode',
			placeholder: 'warehouseCode',
			maxLength: 50,
			textStyle: {},
		},
		refNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'refNum',
			label: 'refNum',
			placeholder: 'refNum',
			maxLength: 100,
			textStyle: {},
		},
		customerPoNum: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'customerPoNum',
			label: 'customerPoNum',
			placeholder: 'customerPoNum',
			maxLength: 100,
			textStyle: {},
		},
		endBuyerUserID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'endBuyerUserID',
			label: 'endBuyerUserID',
			placeholder: 'endBuyerUserID',
			maxLength: 255,
			textStyle: {},
		},
		endBuyerName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'endBuyerName',
			label: 'endBuyerName',
			placeholder: 'endBuyerName',
			maxLength: 255,
			textStyle: {},
		},
		endBuyerEmail: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'endBuyerEmail',
			label: 'endBuyerEmail',
			placeholder: 'endBuyerEmail',
			maxLength: 255,
			textStyle: {},
		},
		shipToName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToName',
			label: 'shipToName',
			placeholder: 'shipToName',
			maxLength: 100,
			textStyle: {},
		},
		shipToCompany: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToCompany',
			label: 'shipToCompany',
			placeholder: 'shipToCompany',
			maxLength: 100,
			textStyle: {},
		},
		shipToAttention: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToAttention',
			label: 'shipToAttention',
			placeholder: 'shipToAttention',
			maxLength: 100,
			textStyle: {},
		},
		shipToAddressLine1: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToAddressLine1',
			label: 'shipToAddressLine1',
			placeholder: 'shipToAddressLine1',
			maxLength: 200,
			textStyle: {},
		},
		shipToAddressLine2: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToAddressLine2',
			label: 'shipToAddressLine2',
			placeholder: 'shipToAddressLine2',
			maxLength: 200,
			textStyle: {},
		},
		shipToCity: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToCity',
			label: 'shipToCity',
			placeholder: 'shipToCity',
			maxLength: 100,
			textStyle: {},
		},
		shipToState: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToState',
			label: 'shipToState',
			placeholder: 'shipToState',
			maxLength: 50,
			textStyle: {},
		},
		shipToStateFullName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToStateFullName',
			label: 'shipToStateFullName',
			placeholder: 'shipToStateFullName',
			maxLength: 100,
			textStyle: {},
		},
		shipToPostalCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToPostalCode',
			label: 'shipToPostalCode',
			placeholder: 'shipToPostalCode',
			maxLength: 50,
			textStyle: {},
		},
		shipToPostalCodeExt: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToPostalCodeExt',
			label: 'shipToPostalCodeExt',
			placeholder: 'shipToPostalCodeExt',
			maxLength: 50,
			textStyle: {},
		},
		shipToCounty: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToCounty',
			label: 'shipToCounty',
			placeholder: 'shipToCounty',
			maxLength: 100,
			textStyle: {},
		},
		shipToCountry: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToCountry',
			label: 'shipToCountry',
			placeholder: 'shipToCountry',
			maxLength: 100,
			textStyle: {},
		},
		shipToEmail: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToEmail',
			label: 'shipToEmail',
			placeholder: 'shipToEmail',
			maxLength: 100,
			textStyle: {},
		},
		shipToDaytimePhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToDaytimePhone',
			label: 'shipToDaytimePhone',
			placeholder: 'shipToDaytimePhone',
			maxLength: 50,
			textStyle: {},
		},
		shipToNightPhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'shipToNightPhone',
			label: 'shipToNightPhone',
			placeholder: 'shipToNightPhone',
			maxLength: 50,
			textStyle: {},
		},
		billToName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToName',
			label: 'billToName',
			placeholder: 'billToName',
			maxLength: 100,
			textStyle: {},
		},
		billToCompany: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToCompany',
			label: 'billToCompany',
			placeholder: 'billToCompany',
			maxLength: 100,
			textStyle: {},
		},
		billToAttention: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToAttention',
			label: 'billToAttention',
			placeholder: 'billToAttention',
			maxLength: 100,
			textStyle: {},
		},
		billToAddressLine1: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToAddressLine1',
			label: 'billToAddressLine1',
			placeholder: 'billToAddressLine1',
			maxLength: 200,
			textStyle: {},
		},
		billToAddressLine2: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToAddressLine2',
			label: 'billToAddressLine2',
			placeholder: 'billToAddressLine2',
			maxLength: 200,
			textStyle: {},
		},
		billToCity: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToCity',
			label: 'billToCity',
			placeholder: 'billToCity',
			maxLength: 100,
			textStyle: {},
		},
		billToState: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToState',
			label: 'billToState',
			placeholder: 'billToState',
			maxLength: 50,
			textStyle: {},
		},
		billToStateFullName: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToStateFullName',
			label: 'billToStateFullName',
			placeholder: 'billToStateFullName',
			maxLength: 100,
			textStyle: {},
		},
		billToPostalCode: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToPostalCode',
			label: 'billToPostalCode',
			placeholder: 'billToPostalCode',
			maxLength: 50,
			textStyle: {},
		},
		billToPostalCodeExt: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToPostalCodeExt',
			label: 'billToPostalCodeExt',
			placeholder: 'billToPostalCodeExt',
			maxLength: 50,
			textStyle: {},
		},
		billToCounty: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToCounty',
			label: 'billToCounty',
			placeholder: 'billToCounty',
			maxLength: 50,
			textStyle: {},
		},
		billToCountry: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToCountry',
			label: 'billToCountry',
			placeholder: 'billToCountry',
			maxLength: 100,
			textStyle: {},
		},
		billToEmail: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToEmail',
			label: 'billToEmail',
			placeholder: 'billToEmail',
			maxLength: 100,
			textStyle: {},
		},
		billToDaytimePhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToDaytimePhone',
			label: 'billToDaytimePhone',
			placeholder: 'billToDaytimePhone',
			maxLength: 50,
			textStyle: {},
		},
		billToNightPhone: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'billToNightPhone',
			label: 'billToNightPhone',
			placeholder: 'billToNightPhone',
			maxLength: 50,
			textStyle: {},
		},
		notes: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'notes',
			label: 'notes',
			placeholder: 'notes',
			maxLength: 1000,
			textStyle: {},
		},
		orderDCAssignmentNum: {
			type: DbComponentEnums.inputTypeEnum.number,
			parentName: 'salesOrderHeaderInfo',
			name: 'orderDCAssignmentNum',
			label: 'orderDCAssignmentNum',
			placeholder: 'orderDCAssignmentNum',
			format: 'number',
			textStyle: {},
		},
		dBChannelOrderHeaderRowID: {
			type: DbComponentEnums.inputTypeEnum.input,
			parentName: 'salesOrderHeaderInfo',
			name: 'dBChannelOrderHeaderRowID',
			label: 'dBChannelOrderHeaderRowID',
			placeholder: 'dBChannelOrderHeaderRowID',
			maxLength: 50,
			textStyle: {},
		},
		//#endregion UI control for SalesOrderHeaderInfo



		//#region UI control for SalesOrderHeaderAttributes
		//#endregion UI control for SalesOrderHeaderAttributes



	},

    grid: {
		salesOrderItems: salesOrderItemsGrid,
    },
    modal: {},
    menu: {},
};

